update

diff --git a/indexopus-3 b/indexopus-3
--- a/indexopus-3
+++ b/indexopus-3
@@ -253,27 +253,54 @@ reindex(){
 
   if [[ ! -f "chapters.json" ]] && ! (( usemetadata )) &&
     confirm "${bold}No chapters.json; retrieve chapter info from the web?${tput0}"; then
+      (( verbose )) && printf '[verbose] in if branch of first if in %s.\n' "$FUNCNAME"
       curl -X POST "$absserver/api/items/$(itemid)/scan"   -H "Authorization: Bearer $abstoken" -sSo /dev/null
       curl "$absserver/api/search/chapters?asin=$(jq -r '.asin' metadata.json)"   -H "Authorization: Bearer $abstoken" -sSo chapters.json
       newchapters=1
   fi
 
-  if [[ -f "chapters.json" ]] && [[ ! $(grep '{"error":"Chapters not found"}' "chapters.json") ]]; then
+  if [[ -f "chapters.json" ]] && [[ ! $(grep '{"error":"Chapters not found"}' "chapters.json") ]] && ! (( usemetadata )); then
+    (( verbose )) && printf '[verbose] in if branch of second if in %s.\n' "$FUNCNAME"
     readarray -t chaptitles < <(jq -r '.chapters[] | .title' "chapters.json" 2>/dev/null)
-    readarray -t chapstarts < <(jq -r '.chapters[] | .startOffsetMs' "chapters.json" 2>/dev/null)
-
-    for ((i=0; i<"${#chapstarts[@]}"; i++)); do
-      sec=$(( chapstarts[i] / 1000 ))
-      ms=$(( chapstarts[i] % 1000 ))
-      chapstarts[i]="${sec}.${ms}"
-    done
-
+## this replacement should make the handing of fp math and different time formats more robust
+#    readarray -t chapstarts < <(jq -r '.chapters[] | .startOffsetMs' "chapters.json" 2>/dev/null)
+#    if [[ "$chapstarts" = null ]]; then
+#      readarray -t chapstarts < <(jq -r '.chapters[] | .start' "chapters.json" 2>/dev/null)
+#    else
+#      for ((i=0; i<"${#chapstarts[@]}"; i++)); do
+#        sec=$(( chapstarts[i] / 1000 ))
+#        ms=$(( chapstarts[i] % 1000 ))
+#        chapstarts[i]="${sec}.${ms}"
+#      done
+##    readarray -t chapstarts < <(jq -r '.chapters[] | (.startOffsetMs // .start)' chapters.json 2>/dev/null)
+#    fi
+    readarray -t chapstarts < <(jq -r '
+      .chapters[] |
+      if .startOffsetMs != null then
+        (.startOffsetMs / 1000) | tostring
+      else
+        (.start // empty) | tostring
+      end
+    ' chapters.json 2>/dev/null)
   else
+    (( verbose )) && printf '[verbose] in else branch of second if in %s.\n' "$FUNCNAME"
 #   need to strip literal `\n` characters from chapter titles otherwise it fucks things up
-    jsonfile="metadata.json"
+    : "${jsonfile:=metadata.json}"
     readarray -t chaptitles < <(jq -r '.chapters[] | .title | gsub("\\n"; " ")' "$jsonfile")
-    readarray -t chapstarts < <(jq -r '.chapters[] | .start' "$jsonfile" 2>/dev/null)
+## this replacement should make the handing of fp math and different time formats more robust
+#    readarray -t chapstarts < <(jq -r '.chapters[] | .start' "$jsonfile" 2>/dev/null)
+    readarray -t chapstarts < <(jq -r '
+      .chapters[] |
+      if .startOffsetMs != null then
+        (.startOffsetMs / 1000) | tostring
+      else
+        (.start // empty) | tostring
+      end
+    ' "$jsonfile" 2>/dev/null)
   fi
+
+  (( verbose )) && for (( i=0; i<"${#chapstarts[@]}"; i++ )); do printf '[verbose] %s\t%s\n' "${chapstarts[i]}" "${chaptitles[i]}"; done
+#  (( verbose )) && printf '[verbose] %s\n' "${starts
 
   chcount=0
   for i in "${chaptitles[@]}"; do [[ "$i" = *Chapter* ]] && ((chcount++)); done
@@ -795,7 +822,7 @@ mvopus(){
 #  if [[ "${opusarray[0]}" =~ .+\ --\ ((C|c)hapter|(P|p)art|(D|d)isc)|(T|t)rack\ [[:digit:]]{1,3}\.opus ]]; then
   if [[ "${opusarray[0]}" =~ .+\ --\ (([Cc]hapter|[Pp]art|[Dd]isc|[Tt]rack)\ [[:digit:]]{1,3})\.opus ]]; then
     echo "Using rename pattern 1."
-   if "${quiet:=false}"; then rmmatch=true; fi
+    if "${quiet:=false}"; then rmmatch=true; fi
 
     for i in "${opusarray[@]}"; do
       n="${i%.opus}"; n="${n##* }"
@@ -968,26 +995,62 @@ mvopus(){
       done
     mvopus
 
-  elif [[ "${opusarray[0]}" =~ ([[:digit:]]{1,3})(: ?|\ |\. ?)(.+\.opus) ]]; then
+  elif [[ "${opusarray[0]}" =~ ([[:digit:]]{1,3})(: ?|\. ?|\ -\ ?|\ ?)((.+)\.opus) ]]; then
+    renpat="6.0"
+    posstitle="${BASH_REMATCH[4]}"
+    for i in "${opusarray[@]}"; do
+      if [[ "$i" =~ ([[:digit:]]{1,3})(: ?|\. ?|\ -\ ?|\ ?)((.+)\.opus) ]]; then
+        [[ "${BASH_REMATCH[4]}" != "${posstitle}" ]] && { unset posstitle; break; }
+      fi
+    done
+    if [[ "$posstitle" ]]; then
+      renpat="$renpat.1"
+      printf 'Using rename pattern %s\n' "$renpat"
+      t="$posstitle"
+
+      regex="([[:digit:]]{1,3})(: ?|\. ?|\ -\ ?|\ ?)((.+)\.opus)"
+      read -rp "This is only marginally functional.  There's still no check for padded digits yet."
+
+      for i in *.opus; do
+        if [[ "$i" =~ $regex ]]; then
+          n="${BASH_REMATCH[1]}"
+          p="Part $n.opus"
+#          p="${BASH_REMATCH[3]}"
+#          [[ "$p" = *\ -\ *.opus ]] && p="${p##* - }"
+#          [[ "$p" = *Chapter\ ?.opus ]] && p="${p/Chapter /Chpater 0}"
+#
+#        ## if "$t" is set via gum input the this if is unnecessary (and could be removed):
+#          if [[ ! "$t" ]]; then
+#            t="$(pwd)"; t="${t##*\/}"
+#            [[ "$t" = *\:* ]] && t="${t%%:*}"
+#            [[ "$t" =~ .+\ \([[:digit:]]{4}\) ]] && t="${t% \(*}"
+#          fi
+#
+          newname="$t -- Part $n: $p"
+          confirmrename["$i"]="$newname"
+        fi
+      done
+    else
+      renpat="$renpat.2"
+      printf 'Using rename pattern %s\n' "$renpat"
 
 ## this pattern matches: `001 Author Name - Book Title - Part Name.opus`
-
-    renpat="6.0"
-
-    printf 'Using rename pattern %s\n' "$renpat"
     printf '\nNB: Using this rename pattern requires setting a title.\n'
 #    printf 'Use the directory in the format of /path/to/dir/Title[: Subtitle [(Year)]]\nPWD: %s\n\n' "$(pwd)"
     t="$(gum input --width="$(( $(tput cols) - $(tput cols)/10 ))" --value="${PWD##*\/}" --header="Enter title to use for part files:")"
     confirm -y "Use $red$iton$t$tput0 as title for part files?" || { printf '\nFix directory name and return.\nExiting. (exit 1)\n\n'; exit 1; }
 
-    regex="([[:digit:]]{1,3})(: ?|\ |\. ?)(.+\.opus)"
+    regex="([[:digit:]]{1,3})(: ?|\. ?|\ -\ ?|\ ?)?(.+\.opus)"
 
     for i in *.opus; do
+      (( verbose )) && printf '[verbose] $i=%s\n' "$i"
       if [[ "$i" =~ $regex ]]; then
         n="${BASH_REMATCH[1]}"
+        (( verbose )) && printf '[verbose] $n=%s\n' "$n"
         p="${BASH_REMATCH[3]}"
         [[ "$p" = *\ -\ *.opus ]] && p="${p##* - }"
         [[ "$p" = *Chapter\ ?.opus ]] && p="${p/Chapter /Chpater 0}"
+        (( verbose )) && printf '[verbose] $p=%s\n' "$p"
 
       ## if "$t" is set via gum input the this if is unnecessary (and could be removed):
         if [[ ! "$t" ]]; then
@@ -1000,6 +1063,9 @@ mvopus(){
         confirmrename["$i"]="$newname"
       fi
     done
+    (( verbose )) && printf %s\\n "${confirmrename[@]}"
+
+    fi
 
 #    printf %s\\n "${confirmrename[@]}"|sort
     mvopus
@@ -1169,6 +1235,7 @@ n="${i#* @(@(C|c)hapter|@(P|p)art|@(T|t)rack|@(D|d)isc) }"; n="${n%% *}"
     renopus=( *\ --\ Part\ *.opus )
     if ! compgen -G '@(*\ --\ Part\ ???\:\ *.opus|*\ --\ Part\ ??\:\ *.opus)' &> /dev/null; then
         pause "Using naming pattern zulu!"
+        printf \\n
         # If files do not match expected naming pattern, attempt to rename them
         if [[ "${renopus[0]/ -- Part / -- Part 00: Part }" == *\ --\ Part\ ??\:\ *.opus ]]; then
         pause "!! USING NAMING PATTERN ZULU !!"
@@ -1183,14 +1250,33 @@ n="${i#* @(@(C|c)hapter|@(P|p)art|@(T|t)rack|@(D|d)isc) }"; n="${n%% *}"
             done
           mvopus
         else
-            allfiles=(*)
-            # Exit if files do not match expected naming pattern and cannot be renamed
-            [[ "${allfiles[@]}" != *.opus\ * ]] && printf 'This directory does not contain files in the expected format or filename.\n'
-            [[ "${allfiles[@]}"  = *.opus\ * ]] && printf 'The rudimentarly built-in file renaming was unable to put the opus files into the pattern of <Title> -- Part ##: <Chapter Title>.opus\nPlease rename files and retry indexopus.'
-            exit
+          allfiles=(*)
+          # Exit if files do not match expected naming pattern and cannot be renamed
+          if [[ "${allfiles[@]}" != *.opus\ * ]]; then
+            printf 'This directory does not contain files in the expected format or filename.\n'
+            exit 1
+          elif [[ "${allfiles[@]}"  = *.opus\ * ]]; then
+            printf 'The rudimentarly built-in file renaming was unable to put the opus files into the pattern of <Title> -- Part ##: <Chapter Title>.opus\n\n'
+            printf 'You can suspend/detatch the script now to drop to shell, rename, to try again...\n\n'
+            printf '$pwd = %s\n     $$ = %s\n' "$(pwd)" "$$"
+            if [[ "$STY" ]]; then
+              printf '   $STY = %s\n' "$STY"
+              pause 'Inside attached screen, you will need to detatch and then rename files.'
+              confirm -Y "Attempt to detach screen programatically?" && screen -S "$STY" -X detach
+            else
+              ppid="$(ps -o ppid= -p $$)"
+              printf '  $ppid = %s\n\n' "$ppid"
+              confirm -Y "Attempt to suspend with kill -SIGSTP $ppid?" && kill -SIGTSTP "$(ps -o ppid= -p $$)"
+            fi
+            confirm -Y "Attempt to use standard naming pattern?" || exit 130
+            pause "Still need to insert a test of the renamed files!!!"
+          fi
         fi
      fi
+  (( verbose )) && printf 'Leaving rename()\n'
 }
+
+##--> rename <--####################################################################
 
 
 ##--> Main Code<--#####################################################################
@@ -1234,8 +1320,8 @@ while [[ "$#" -gt 0 ]]; do
      fi
   elif [[ "$1" = @(-r|--reindex|reindex) ]]; then
     reindex=true
-  elif [[ "$1" = --reindex=metadata.json ]]; then
-    reindex=true; usemetadata=1
+  elif [[ "$1" = --reindex=*.json ]]; then
+    reindex=true; usemetadata=1; jsonfile="${1/--reindex=}"
   elif [[ "$1" = @(-h|help|--help) ]]; then
     usage
   else
diff --git a/mp32opus-1 b/mp32opus-1
--- a/mp32opus-1
+++ b/mp32opus-1
@@ -12,27 +12,174 @@ boldred="$(tput bold setaf 9)"
 red="$(tput setaf 1)"
 relipsis="${red}..."
 tmpdir=/cache
+discord=1
 #rmmatch=1
 
 ## source functions #################################################################################
 . /usr/local/bin/editscript
 sourcefn -l /usr/local/bin/indexopus.lib -f sex2sec -f printline -f confirm
 
+
+## functions ########################################################################################
+
+filecheck(){
+(( verbose )) && printf '[verbose] Entering filecheck().\n'
+  local clifilename clipath startm4a mvoutput mvec  ## not sure what to do here.  need to see the scope of these variables.
+  [[ -e "$1" ]] && clifilename="$(realpath "$1")"  #if a filename is passed via the cli.  this doesn't work anymore now with -t??
+(( verbose )) && read -rp "[verbose] \$clifilename: ${clifilename:-null}"
+  [[ -d "$clifilename" ]] && clipath="${clifilename%/}" && cd "$clipath" && unset clifilename
+  [[ -f "$clifilename" ]] && clipath="${clifilename%/*}" && cd "$clipath" && clifilename="${clifilename##*/}" ## add an || unset clifilename here?
+(( verbose )) && read -rp "[verbose] \$clifilename: ${clifilename:-null}"
+(( verbose )) && read -rp "[verbose] \$clipath: ${clipath:-null}"
+
+#  if [[ "$clipath" ]]; then
+#    [[ -d "$clipath" && ! -w "$clipath" ]] && { own "$clipath" || { printf 'Cannot take ownership of %s. Investigate. (exit 1)' "$clipath"; exit 1; }; }
+
+  if ! [[ -w . ]]; then
+    printf '\n[WARN] The pwd (%s) is not writable;\n  attempting to take ownership.\n\n' "$(pwd)"
+    (( verbose )) && pause "$(type own) $(which own)"
+    own .
+    if ! [[ -w . ]]; then
+      (( verbose )) && printf '\n[WARN] The `own .` command failed\n\nTrying `sudo chown $USER .`\n\n' &&
+      eza -glaa .
+      if ! sudo -n chown -R "$USER":"${group:-$USER}" .; then
+        (( verbose )) && printf '[WARN] The `sudo -n chown -R "%s":"%s" .` command failed!\n' "$USER" "${group:-$USER}"
+        (( discord )) && discorddm "m4b2opus: Attention required! confirm \`sudo chown \"$USER\" .\`"
+#       apprise "$apprisediscord" -t "Attention required m4b2opus!" -b "confirm \`sudo chown \"$USER\" .\`"
+        sudo chown -R "$USER":"${group:-$USER}" . || { printf '[ERROR] Cannot take ownership of %s. Investigate. (exit 1)\n' "$clipath"; exit 1; }
+      fi
+    fi
+    ! [[ -w . ]] && { printf '[ERROR] Cannot take ownership of %s. Investigate. (exit 1)\n' "$clipath"; exit 1; } || printf '\nOwnership of pwd granted to %s.\n' "$USER"
+  fi
+
+##  [[ "$clifilename" = *\ --\ Audiobook.m4b ]] && [[ -f "$1" ]] && m4bin="$1" && return 0
+#  [[ "$clifilename" = *\ --\ Audiobook.m4b ]] && [[ -f "$clifilename" ]] && { m4bin="$clifilename"; return 0; }
+#
+### at this point the pwd should either be the swd or it should be the local "$clipath" from the cd "$clipath" above.
+#(( verbose )) && read -rp "[verbose] \$(pwd): $(pwd)"
+#
+#  [[ "$clifilename" ]] && files=("$clifilename") || files=(*.m4[ba])
+#
+#(( verbose )) && read -rp "[verbose] \${files[@]}: $(printf %s\\n "${files[@]}")"
+#
+#    if (( "${#files[@]}" == 1 )); then
+#
+#      # to handle the case where there's an unindexed m4a or a misnamed m4b,
+#      # for simplicity sake, just rename to m4b
+#      # probably want to change it back at the end, but it is going to get deleted anyway
+#      if [[ "${files[0]}" = *.m4a ]]; then
+#        startm4a="${files[0]}"
+#        startfile="$startm4a"
+#        files[0]="${files[0]%.m4a}.m4b"
+#        mv "$startm4a" "${files[0]}"
+#        (( "$?" )) && { printf 'The starting file was an m4a which could not be renamed to m4b:\n mv %s %s\nInvestigate. (return 1)' "${startm4a@Q}" "${files[0]@Q}"; return 1; }
+#      fi
+#
+#      if [[ "${files[0]}" = *\ --\ Audiobook.m4b ]]; then
+#        m4bin="${files[0]}"
+#      elif [[ "${files[0]}" = *.m4b ]]; then
+#        m4bin="${files[0]}"
+###        startfile="${files[0]}"
+###   is there any reason I need to do this?
+###   could I make this conditional on ! (( save ))?
+###        m4bin="${files[0]/.m4b/ -- Audiobook.m4b}"
+###        mvoutput="$(mv "${files[0]}" "$m4bin" 2>&1)"
+#        mvec="$?"
+#        if (( mvec > 0 )); then
+#          if [[ "$mvoutput" = "mv: cannot move "*": Permission denied" ]]; then
+#            own && mv "${files[0]}" "$m4bin" || { printf 'Unable to gain write permission for %s. exit 1\n\n' "${files[@]}"; exit 1; }
+#          else
+#            printf 'Unknown error renaming %s. exit 1\n\n' "${files[@]}"
+#            exit 1
+#          fi
+#        fi
+#      else
+#        printf 'The file passed to the script was not an *m4[a|b]:\n %s\n.  This cannot be allowed to stand!\n\nInvestigate. (return 1)\n' "$1"
+#        return 1
+#      fi
+#    else
+#      printf 'No single m4b/m4a input file found or specified, please check and retry...\n\n'
+#      eza -laa --no-user
+#      printf '\n(exit 1)\n\n'
+#      exit 1
+#    fi
+
+(( verbose )) && { printf '[verbose] Leaving filecheck():\n'; pause "          \$m4bin: $m4bin"; }
+#  fi
+return 0
+}
+##--> filecheck() <--#################################################################################
+
+extractcover(){
+  local file="$1"
+  if mediainfo "$1"|grep -A1 '^Image'|grep -qE '^Type\s+:\s+Cover';  then
+    coverfile="${file%.*} -- Cover.jpg"
+    (( verbose )) &&
+     { printf 'Source file = %s\n' "$file"
+       printf ' Cover file = %s\n' "$coverfile"
+       printf '\nMediaInfo of source file:\n'
+       readarray -t miout < <(mediainfo "$file")
+       printf '     %s\n' "${miout[@]}"; }
+    (( verbose )) && read -rp "$file $coverfile"
+    ffmpegcmd=( ffmpeg -i "$file" -an -update 1 -frames:v 1 "file:$coverfile" -y )
+    if [[ -f "$coverfile" ]]; then
+      if (( rmmatch )) || [[ "$STY" ]]; then
+        mv "$coverfile" "$coverfile~"
+        ffmpegcmd+=(-y)  ## probably unnecessary, but do not want to hold up screened process
+        printf 'File %1$s exists. Moving to %1$s~ and extracting cover.\n' "$coverfile"
+      else
+        (( verbose )) &&
+         { printf 'MediaInfo of existing cover file:\n' "$coverfile"; readarray -t miout < <(mediainfo "$coverfile"); printf '     %s\n' "${miout[@]}"; }
+        confirm "$(printf 'Overwrite existing cover file?' "$coverfile")" && ffmpegcmd+=(-y) ||
+          printf 'Not overwriting existing cover file. (return 1)'
+      fi
+    fi
+
+    (( verbose )) && printf 'ffmpeg call: %s\n' "${ffmpegcmd[*]}"
+
+    if (( verbose )); then "${ffmpegcmd[@]}"
+    else "${ffmpegcmd[@]}" &> /dev/null; fi
+
+    ec="$?"
+
+    (( verbose )) && { readarray -t miout < <(mediainfo "$coverfile"); printf '     %s\n' "${miout[@]}"; }
+    printf %s\\n "$coverfile"
+  else
+    printf 'No embedded cover found in: %s\n' "$file" >&2
+    return 1
+  fi
+}
+
+##--> extractcover() <--#############################################################################
+
+## flag processing ###################################################################################
+
 args=(mp32opus)
 
 while (( $# > 0 )); do
-  [[ "$1" = "--edit"        ]] && editscript && exit
-  [[ "$1" = @(--screen|-s)  ]] && { screened=1; shift; continue; }
-  [[ "$1" = "-y"            ]] && { args+=("$1"); rmmatch=1; shift; continue; }
-  [[ "$1" = "-n"            ]] && { args+=("$1"); no=1; unset rmmatch; shift; continue; }
-  [[ "$1" = "--stats"       ]] && { args+=("$1"); stats=true; shift; continue; }
-  [[ "$1" = @(-ys|-yes)     ]] && { args+=("-y"); (( screened=rmmatch=1 )); shift; continue; }
-  [[ "$1" = "--save"        ]] && { args+=("$1"); save=1; shift; continue; }
-  [[ "$1" = @(-D|--discord) ]] && { args+=("$1"); discord=1; . ~/.config/apprise.conf; shift; continue; }
+  [[ "$1" =         "--edit" ]] && editscript && exit
+  [[ "$1" =             "-y" ]] && { args+=("$1"); args+=(--save); (( save=rmmatch=1 )); shift; continue; }
+  [[ "$1" =             "-Y" ]] && { args+=("$1"); rmmatch=1; shift; continue; }
+  [[ "$1" =             "-n" ]] && { args+=("$1"); no=1; unset rmmatch; shift; continue; }
+  [[ "$1" =         "--save" ]] && { args+=("$1"); save=1; shift; continue; }
+  [[ "$1" =        "--stats" ]] && { args+=("$1"); stats=1; shift; continue; }
+  [[ "$1" =   @(--screen|-s) ]] && { screened=1; shift; continue; }
+  [[ "$1" = @(-|--)@(ys|yes) ]] && { args+=("-y"); (( screened=rmmatch=1 )); args+=(--save); shift; continue; }
+  [[ "$1" = @(-|--)@(Ys|Yes) ]] && { args+=("-Y"); (( screened=rmmatch=1 )); shift; continue; }
+  [[ "$1" =  @(-v|--verbose) ]] && { args+=("$1"); verbose=1; shift; continue; }
+  [[ "$1" =  @(-D|--discord) ]] && { args+=("$1"); unset discord; . ~/.config/apprise.conf; shift; continue; }
   [[ -d "$1" ]] && { args+=("$1"); clipath="$1"; clidir="$1"; shift; continue; }
   [[ -f "$1" ]] && { args+=("$1"); clipath="$1"; clifile="$1"; shift; continue; }
-  { printf '%s is unrecognized.\n' "$1"; shift; confirm -y 'Proceed with script?' || exit 1; }
+  { printf '"%s" is unrecognized.\n' "$1"; shift; confirm -y 'Proceed with script?' || exit 1; }
 done
+
+[[ ! "$clifile" ]] && { allm4s=(*.m4[ab])
+                        printf '\n%s/*.m4[ab]: \n%s' "$(pwd)" "$red"
+                        printf ' %s\n' "${allm4s[@]}"
+                        printf '%s' "$white"; }
+
+filecheck "${clifile:-""}"
+(( "$?" )) && { printf 'The files failed filecheck()!\nInvestigate (exit 1)\n.'; exit 1; }  # this function returns "$m4bin"
 
 printline "$bold  Welcome to ${0##*\/}  $tput0"
 printf \\n
@@ -40,12 +187,23 @@ printf \\n
 if (( screened )); then
   printline "$bold Calling ${args[*]} in GNU screen $tput0"
   printf \\n\\n
-## this needs to be fixed:
-  screenname="mp32opus-${PWD##*/}"
-  ! (( no )) && args+=(-y)
+
+  if (( verbose )) && { confirm -y "$0 was called to screen with verbose on.\nThis may result in stops in the script while in screen.\nTurn verbose off?"; printf \\n\\n; }; then
+     for i in "${!args[@]}"; do
+       [[ "${args[i]}" = '-v' ]] && unset 'args[i]'
+     done
+     args=("${args[@]}")       ## compact array
+  fi
+
+## this needs to be checked:
+  [[ "$clipath" ]] && screenname="mp32opus-$(basename "$clipath")" ||
+    screenname="mp32opus-${PWD##*/}"
+  ! (( no )) && [[ " ${args[*]} " != *\ -Y\ * ]] && args+=("-y")
   printf '%s ' "${args[@]}"
   printf \\n
-  screen -dmS "${screenname:0:16}" "${args[@]}"
+#  screen -dmS "${screenname:0:16}" "${args[@]}"
+#  screen -dmS "${screenname:0:16}" bash -i -c "$(printf '%q ' "${args[@]}")"
+  screen -dmS "${screenname:0:16}" bash -i "${args[@]}"
   screen -ls                                     #could probably add some logic to not delete shit
   printf \\n\\n                                  #leaving that for later, but screen implies -y as
   exit                                           #it doesn't really work otherwise?
@@ -62,10 +220,18 @@ allfiles=(*.@(mp3|m4@(a|b)))
 [[ "$rmmatch" ]] && args=("-y") || unset args  #this resets args from "$@"
 
 if [[ "$clifile" ]] || (( "${#allfiles[@]}" == 1 )); then
-  args+=("$clifile")
-(( verbose )) &&  pause "$(printf quartero4\ %s\\n "${args[@]}")"
+  (( save )) && args+=(--save)
+  (( verbose )) && args+=(-v)
+  args+=(-D) ## unset the discord flag since this should be doing the notification.
+  [[ "$clifile" ]] && args+=("$clifile")
+  (( verbose )) &&  pause "$(printf quartero4\ %s\\n "${args[*]}")"
   printline "${bold}  Calling ${white}quartero4 ${args[@]}  ${tput0}"
+#  args=(quartero4 "${args[@]}")
+#  printline "${bold}  Calling ${white}${args[*]}${tput0} "
   quartero4 "${args[@]}"
+#  "${args[@]}"
+  ec="$?"
+  (( ec )) && { printf '[ERROR] quartero4 %s did not exit cleanly. Investigate. (exit %s)\n' "${args[*]}" "$ec"; exit "$ec"; }
 else
   printline "$bold  $(pwd):  $tput0"
   eza -l --no-user
@@ -78,7 +244,11 @@ else
 ## this check is a false sense of security as there's no way at present to check if there's not more than
 ## one book in the same format
 
-  (( "${#initdurations[@]}" != 1 )) && { printf 'There are more than two different formates reported by mediaduration and automatic deletion cannot proceed. Investigate.\n'; confirm "Continue?"; rmmatch=0; }
+  (( "${#initdurations[@]}" != 1 )) &&
+   { printf 'There are more than two different formates reported by mediaduration and automatic deletion cannot proceed. Investigate.\n';
+     confirm "Continue?" || exit 130; rmmatch=0; }
+
+  (( "${#initdurations[@]}" == 1 )) && ext="${initdurations[0]#*.}" && ext="${ext%% *}"
 
   tmpdir="$tmpdir/mp32opus-${PWD##*/}"
 
@@ -93,8 +263,14 @@ else
   { mkdir -p "$tmpdir" && cd "$tmpdir"; } || { printf 'Failure of `mkdir/cd %s` occurred! Investigate. (exit 1)\n' "$tmpdir"; exit 1; }
 
   eza -gla --no-user
-(( verbose)) &&  pause "pwd=$PWD"
+  (( verbose )) && args+=('-v')
+  (( verbose )) && pause "\$args=$(printf %s\\n "${args[@]}")"
+  (( verbose )) && pause "pwd=$PWD"
   indexopus "${args[@]}"
+  ec="$?"
+  (( ec )) && (( ec == 1 )) && { printf '\nThe indexopus script did not exit cleanly. Investigate. (exit %s)\n\n' "$ec"; exit "$ec"; } # i don't know for sure that the ec from indexopus can\'t be other than 0, 1, 2.
+  (( ec == 2 )) && iorm=true # this is something that is part of the m4b2opus integration with indexopus.  iorm *probably* means "indexopus rm" such that the user's said yes to a prompt to remove shit.
+
 #readarray -t durations < <(mediaduration|sed 's/^[^:]*: //')
 
   [[ "$tmpdir" ]] && mv *\ --\ Audiobook.opus "$swd"
@@ -103,7 +279,13 @@ else
 
   tmpdirfiles=(*)
   ## the tmpdir should have been emptied already...try to remove it now if so...
-  ! (( "${#tmpdirfiles[@]}" )) && { pause "Removing $tmpdir; this confirmation needs to be removed eventually."; rmdir "$tmpdir"; }
+  if (( "${#tmpdirfiles[@]}" )); then
+    eza -gla --no-user --color=always "$tmpdir"
+    printf \\n
+    confirm "The temp directory ($tmpdir) is not empty! Remove anyway?" && rmdir "$tmpdir"
+  else
+    rmdir "$tmpdir"
+  fi
 
 
 ## This is yet to be implemented in opus.book.4 as above...
@@ -115,7 +297,7 @@ else
   readarray -t durations < <(mediaduration)
   printf %s\\n "${durations[@]}"
 
-(( "${#durations[@]}" != 2 )) && { printf 'There are more than two different formates reported by mediaduration and automatic deletion cannot proceed. Investigate.\n'; confirm "Continue?"; rmmatch=0; }
+  (( "${#durations[@]}" != 2 )) && { printf 'There are not exactly two different formats reported by mediaduration and automatic deletion cannot proceed. Investigate.\n'; confirm "Continue?"; rmmatch=0; }
 
   [[ "${durations[-1]}" != Duration\ of\ .opus\ files* ]] && noopus=1
 
@@ -125,7 +307,7 @@ else
       break
     done
     (( noopus )) &&
-      { printf 'There was no opus duration found by mediaduration. Investigate. (exit 1)';
+      { printf 'There was no opus duration found by mediaduration. Investigate. (exit 1)\n\n';
         exit 1; }
   fi
 
@@ -136,9 +318,11 @@ else
   opusdursec="$(sex2sec "$opusdur")"
   sourcedursec="$(sex2sec "$sourcedur")"
 
+
   title=(*\ --\ Audiobook.opus)
   (( "${#title[@]}" == 1 )) && title="${title% -- Audiobook.opus}"
   ioutput="$(tput sitm)$title$(tput ritm) -- Audiobook.opus"
+  read -rp "$(printf '[verbose] title: %s\n' "$title")"
 
   if (( opusdursec > 0 )); then
     verifydur=$(( (1000 * (sourcedursec - opusdursec)) / opusdursec ))
@@ -147,13 +331,14 @@ else
     printf \\n
 
     if (( verifydur <= 1 )); then  #this is 0.1% difference
-      { (( rmmatch )) || confirm -y "Durations are within 0.1%.\n  $(ls *mp3) \n\nRemove starting mp3 files?"; } && { rm *.mp3; rmdir "$tmpdir"; }
+      { (( rmmatch )) || confirm -y "Durations are within 0.1%.\n$(ls *$ext) \n\nRemove starting $ext files?"; } && ! (( save )) && { rm -vf *."$ext"; rmdir "$tmpdir"; }
       [[ "$sourcedursec" != "$opusdursec" ]] &&
          printf '\n%sDurations don'\''t %sexactly%s match but fuckin'\'' close '\''nuff!%s\n' "$relipsis" "$(tput sitm)" "$(tput ritm)" "$tput0" ||
          printf '%sDurations match!%s\n' "$relipsis" "$tput0"
       printf '\n%sDone.\n\nPlease see %s/%s%s\n\n' "$relipsis" "$(pwd)" "$ioutput" "$tput0"
-      (( discord )) && apprise "$apprisediscord" -t "$(basename "$0") completed:" -b "${title:-title unavailable}"
-      exit
+#      (( discord )) && apprise "$apprisediscord" -t "$(basename "$0") completed:" -b "${title:-title unavailable}"
+     (( discord )) && discorddm "mp32opus completed: ${title:-title unavailable}"
+     exit
     elif (( rmmatch )) && (( verifydur )); then
       printf '%s%sThe source and opus audiobook durations do not match!\n' "$bold" "$red"
       printf '%s%s%s will not automatically delete starting and temporary files!\n' "$white" "$tput0" "$0"
@@ -172,4 +357,6 @@ else
 fi
 
 
-(( discord )) && apprise "$apprisediscord" -t "$(basename "$0") completed:" -b "${title:-title unavailable}"
+#(( discord )) && apprise "$apprisediscord" -t "$(basename "$0") completed:" -b "${title:-title unavailable}"
+
+(( discord )) && discorddm "mp32opus completed: ${title:-${allfiles[0]:-title unavailable}}"
