update

diff --git a/indexopus b/indexopus
--- a/indexopus
+++ b/indexopus
@@ -33,7 +33,7 @@ bold="$(tput bold)" #bold on
 relipsis="$red..."
 stamp="$(date +%s)"  #sets datecode for all of indexopus - could use info from m4b2opus later
 tmp="/tmp/indexopus-$stamp" #this could change based on info from m4b2opus
-remove_mp4tags=("major_brand" "minor_version" "compatible_brands" "encoded_by" 'OverDrive\ MediaMarkers' "handler_name" "vendor_id")
+remove_mp4tags=("major_brand" "minor_version" "compatible_brands" "encoded_by" 'OverDrive MediaMarkers' "handler_name" "vendor_id")
 
 editscript(){
   local script path; script="${scriptpath##*/}"; path="${scriptpath%/*}"; swp="$path/.$script.swp"
@@ -192,8 +192,7 @@ reindex(){
 
   if [[ ! -f "chapters.json" ]]; then
     if confirm "${bold}No chapters.json; retrieve chapter info from the web?${tput0}"; then
-#      printf '$s\n%s' 'curl -X POST "$absserver/api/items/$(itemid)/scan"   -H "Authorization: Bearer $abstoken"' $(curl -X POST "$absserver/api/items/$(itemid)/scan"   -H "Authorization: Bearer $abstoken")
-#      printf '%s\n%s' $(curl "$absserver/api/search/chapters?asin=$(jq -r '.asin' metadata.json)"   -H "Authorization: Bearer $abstoken" >chapters.json) 'curl "$absserver/api/search/chapters?asin=$(jq -r '.asin' metadata.json)"   -H "Authorization: Bearer $abstoken" >chapters.json'
+
       curl -X POST "$absserver/api/items/$(itemid)/scan"   -H "Authorization: Bearer $abstoken" -sSo /dev/null
       curl "$absserver/api/search/chapters?asin=$(jq -r '.asin' metadata.json)"   -H "Authorization: Bearer $abstoken" -sSo chapters.json
       newchapters=true
@@ -203,11 +202,12 @@ reindex(){
   if [[ -f "chapters.json" ]] && [[ ! $(grep '{"error":"Chapters not found"}' "chapters.json") ]]; then
     readarray -t chap_titles < <(jq -r '.chapters[] | .title' "chapters.json" 2>/dev/null)
     readarray -t chap_starts < <(jq -r '.chapters[] | .startOffsetMs' "chapters.json" 2>/dev/null)
-  for ((i=0; i<"${#chap_starts[@]}"; i++)); do
-    sec=$(( chap_starts[i] / 1000 ))
-    ms=$(( chap_starts[i] % 1000 ))
-    chap_starts[i]="${sec}.${ms}"
-  done
+
+    for ((i=0; i<"${#chap_starts[@]}"; i++)); do
+      sec=$(( chap_starts[i] / 1000 ))
+      ms=$(( chap_starts[i] % 1000 ))
+      chap_starts[i]="${sec}.${ms}"
+    done
 
   else
     readarray -t chap_titles < <(jq -r '.chapters[] | .title' "metadata.json" 2>/dev/null)
@@ -257,30 +257,36 @@ reindex(){
   printf '%s\t\t\t\t : %s\n' "${rawindex[@]}"
 # printf '%s                             : %s\n' "${rawindex[@]}"
   itemid_pwd
-  itemid="$(sqlite3 "$abssqlite" "select id FROM libraryitems WHERE path=='$sqlitepwd';")"
-  printf '%s\n%sThis index was generated from existing %s;\n' "$tput0" "$relipsis" "$jsonfile"
-  [[ "$itemid" ]] && printf '...look up new chapter information at\ngoogle-chrome %s/audiobook/%s/chapters\n\n\n' "$absserver" "$itemid"
-  [[ ! "$itemid" ]] && printf '%s%s not found in absdatabase.sqlite!%s\n%sCheck path and metadata.json file\n\n\n' "$bold" "$PWD" "$tput0" "$red"
-
-  if [[ "$rmmatch" = true ]]; then
-    writeindex "$reintitle"
-    [[ "$newchapters" = true ]] && curl -X POST "$absserver/api/items/$(itemid)/scan" -H "Authorization: Bearer $abstoken"
-  elif confirm "${bold}${red}Apply index? ${tput0}"; then
-    writeindex "$reintitle"
-    [[ "$newchapters" = true ]] && curl -X POST "$absserver/api/items/$(itemid)/scan" -H "Authorization: Bearer $abstoken"
-    rmmatch=true  #at this point, having said yes to apply index, yes the rest of the way.
+  readarray -t itemids < <( sqlite3 "$abs_sqlite" "select id FROM libraryitems WHERE path=='$sqlitepwd';" )
+  if (( ${#itemids[@]} > 1 )); then
+    printf '\n%s%saudiobookself reports more than one matching title; investigate: %s\n' "$red" "$bold" "$tput0"
+    for itemid in "${itemids[@]}"; do
+    printf '%s/item/%s\n' "$absserver" "$itemid"
+    done
   else
-    mediainfo "$reintitle"
-    printf '%s\t\t\t\t : %s\n' "${rawindex[@]}"
-    if confirm "Would you like to start over so you can look up chapter information in audiobookshelf?"; then
-      indexopus reindex
-      exit
-    else
-      printf 'Not reindexing opus file with above index; exiting.'
-      exit
-    fi
-  fi
+    printf '%s\n%sThis index was generated from existing %s;\n' "$tput0" "$relipsis" "$jsonfile"
+    [[ "$itemids" ]] && printf '...look up new chapter information at\ngoogle-chrome %s/audiobook/%s/chapters\n\n\n' "$absserver" "$itemids"
+    [[ ! "$itemids" ]] && printf '%s%s not found in absdatabase.sqlite!%s\n%sCheck path and metadata.json file\n\n\n' "$bold" "$PWD" "$tput0" "$red"
 
+    if [[ "$rmmatch" = true ]]; then
+      writeindex "$reintitle"
+      [[ "$newchapters" = true ]] && curl -X POST "$absserver/api/items/$(itemid)/scan" -H "Authorization: Bearer $abstoken"
+    elif confirm "${bold}${red}Apply index? ${tput0}"; then
+      writeindex "$reintitle"
+      [[ "$newchapters" = true ]] && curl -X POST "$absserver/api/items/$(itemid)/scan" -H "Authorization: Bearer $abstoken"
+      rmmatch=true  #at this point, having said yes to apply index, yes the rest of the way.
+    else
+      mediainfo "$reintitle"
+      printf '%s\t\t\t\t : %s\n' "${rawindex[@]}"
+      if confirm "Would you like to start over so you can look up chapter information in audiobookshelf?"; then
+        indexopus reindex
+        exit
+      else
+        printf 'Not reindexing opus file with above index; exiting.'
+        exit
+      fi
+    fi
+ fi
   mediainfo *Audiobook.opus
   rm -rf "$tmp"
 
@@ -292,6 +298,10 @@ writeindex(){
   local output="$1" mp4grep mp4opustags chaptag tags ck4tags args
   [[ ! "$remove_mp4tags" ]] &&
      remove_mp4tags=("major_brand" "minor_version" "compatible_brands" "encoded_by" "OverDrive MediaMarkers")
+
+#pause "$(printf %s\\n "${remove_mp4tags[@]}")"
+
+
 #this works, why won't it work in the array?
 # opustags -d "OverDrive MediaMarkers" -i "$output"
   if [[ "$(opustags "$output")" = *CHAPTER* ]]
@@ -337,59 +347,19 @@ writeindex(){
     done
 
     mp4args+=(-i "$output")    # Should I also use readarray here?  difference?
-    opustags "${args[@]}"
+    opustags "${mp4argss[@]}"
   fi
 
 }
 
+
 ##--> writeindex() <--#################################################################################
 
-
-#rename() {
-#   if compgen -G @(*\ --\ Chapter\ ??*.opus|*\ --\ Disc\ ??.opus|*-Part??.opus) &> /dev/null
-#     then
-#       for renopus in *Chapter\ ??*.opus; do [[ -f "$renopus" ]] && mv "$renopus" "${renopus/ Chapter / Part }"; done
-#       for renopus in *Disc\ ??.opus; do [[ -f "$renopus" ]] && mv "$renopus" "${renopus/ Disc / Part }"; done
-#       for renopus in *-Part??.opus; do [[ -f "$renopus" ]] && mv "$renopus" "${renopus/-Part/ -- Part 00: Part }"; done
-#   else
-#     ext=opus
-#
-#     if [[ "$rmmatch" != true ]]; then
-#       confirm "Continue with proposed rename?" &&
-#       for i in *\ -\ ??.opus *\ -\ ???.opus; do mv "$i" "${i/ - / -- Part }"; done ||
-#       exit  # Exit on fail
-#     else
-#       for i in *\ -\ ??.opus *\ -\ ???.opus; do mv "$i" "${i/ - / -- Part }"; done ||
-#       exit  # Exit on fail
-#     fi
-#
-##     if [[ "${opusarray[@]}" =~ '^(.+ - \d{2}\.opus)$' ]]; then
-# #  fi
-#   fi
-#  renopus=( *\ --\ Part\ *.opus )
-#
-##  if [[ "${renopus[0]}" != @(*\ --\ Part\ ???\:\ *.opus|*\ --\ Part\ ??\:\ *.opus) ]]
-#  if ! compgen -G @(*\ --\ Part\ ???\:\ *.opus|*\ --\ Part\ ??\:\ *.opus) &> /dev/null
-#    then
-#      if [[ "${renopus[0]/ -- Part / -- Part 00: Part }" == *\ --\ Part\ ??\:\ *.opus ]]
-#        then
-#          for i in *opus
-#            do
-#              n="${i#* -- Part }"; n="${n%%.opus}"
-#              mv "$i" "${i/ -- Part / -- Part $n: Part }"
-#            done
-#        else
-#          printf 'This directory does not contain files in the format of %s<Title>%s -- Part ##:<Chapter Title>.opus\nPlease check the directory this script was launched from to make sure it contains the proper files.\n' "${iton}" "${itoff}"
-#          exit
-#      fi
-#   fi
-#
-#}
 rename() {
 ext=opus #local?
+declare -A confirm_rename
 
 if [[ "${opusarray[@]}" =  *\ --\ @(Chapter|Part|Disc)\ @(??|???).opus* ]]; then
-    declare -A confirm_rename
     for i in "${opusarray[@]}"; do
         n="${i%.opus}"; n="${n##* }"
         title="${i% -- *}"
@@ -400,29 +370,12 @@ if [[ "${opusarray[@]}" =  *\ --\ @(Chapter|Part|Disc)\ @(??|???).opus* ]]; then
         printf '%s    %s---->%s    %s%s\n%s' "$i" "$bold" "$tput0" "$red" "$newname" "$tput0"
     done
     echo
-
     # Confirm the rename
     [[ ! "$rmmatch" ]] && confirm "${bold}Continue with Proposed Rename? (y/n) " &&
     for i in "${!confirm_rename[@]}"; do
-        [[ "$i" = *\ @(Chapter|Disc)\ @(??|???).opus ]] &&
+      [[ "$i" = *\ @(@(C|c)hapter|@(D|d)isc|@(P|p)art)\ @(??|???).opus ]] &&
         mv "$i" "${confirm_rename["$i"]}"
     done || exit
-
-#  if [[ "${opusarray[@]}" =  *\ --\ @(Chapter|Part|Disc)\ @(??|???).opus* ]]; then
-#    for i in "${opusarray[@]}"; do
-#      n="${i%.opus}"; n="${n##* }"
-#
-#      [[ "$i" = *\ @(Part|Chapter|Disc)\ @(??|???).opus ]] &&
-#        newname="${i/ @(Part|Chapter|Disc) / Part $n: Part }"
-#          printf '%s    %s---->%s    %s%s\n%s' "$i" "$bold" "$tput0" "$red" "$newname" "$tput0"
-#    done
-#          echo
-#     confirm "${bold}Continue with Proposed Rename" &&
-#        for i in *\ @(Part|Chapter|Disc)\ @(??|???).opus; do
-#          n="${i%.opus}"; n="${n##* }"
-#          [[ "$i" = *\ @(Chapter|Disc)\ @(??|???).opus ]] &&
-#            mv "$i" "${i/ @(Chapter|Disc) / Part $n: Part }"
-#        done
 
   elif [[ "${opusarray[@]}" = *-Part@(??|???).opus ]]; then
     for i in *-Part??.opus; do
@@ -437,14 +390,12 @@ if [[ "${opusarray[@]}" =  *\ --\ @(Chapter|Part|Disc)\ @(??|???).opus* ]]; then
         [[ "$i" = *\ @(Chapter|Disc)\ @(??|???).opus ]] &&
           mv "$i" "${i/-Part/ -- Part $n: Part }"
        done
-else
+elif [[ "${opusarray[@]}" =~ .+[[:space:]]-[[:space:]][[:digit:]]{1,3}\.opus ]]; then
     regex=".+[[:space:]]-[[:space:]][[:digit:]]{1,3}\.opus"
       for i in *\ -\ @(?|??|???).opus; do
-        if [[ -f "$i" && "${opusarray[@]}" =~ $regex ]]; then
           n="${i%.opus}"; n="${n##* - }"
           newname="${i/ - / -- Part $n: Part }"
           printf '%s    %s---->%s    %s%s\n%s' "$i" "$bold" "$tput0" "$red" "$newname" "$tput0"
-        fi
       done
         if [[ "$rmmatch" != true ]]; then
             # Ask for confirmation before renaming
@@ -459,7 +410,24 @@ else
             done ||
             exit
         fi
-    fi
+elif [[ "${opusarray[@]}" =~ .+[[:space:]][[:digit:]]{1,3}\.opus ]]; then
+#    regex=".+[[:space:]]-[[:space:]][[:digit:]]{1,3}\.opus"
+    regex=".+[[:space:]][[:digit:]]{1,3}\.opus"
+    for i in "${opusarray[@]}"; do
+          n="${i%.opus}"; n="${n##* }"
+          newname="${i% *}"; newname="$newname -- Part $n: Part $n.opus"
+          printf '%s    %s---->%s    %s%s\n%s' "$i" "$bold" "$tput0" "$red" "$newname" "$tput0"
+          confirm_rename["$i"]="$newname"
+    done
+    echo
+    # Confirm the rename
+    [[ ! "$rmmatch" ]] && confirm "${bold}Continue with Proposed Rename? (y/n) " &&
+    for i in "${!confirm_rename[@]}"; do
+     [[ "$i" =~ $regex ]] &&
+        mv "$i" "${confirm_rename["$i"]}"
+    done || exit
+
+fi
 
     # Check if files match the expected naming pattern after renaming
     renopus=( *\ --\ Part\ *.opus )
@@ -471,11 +439,14 @@ else
                 mv "$opusfile" "${opusfile/ -- Part / -- Part $n: Part }"
             done
         else
+            allfiles=(*)
             # Exit if files do not match expected naming pattern and cannot be renamed
-            printf 'This directory does not contain files in the expected format.\n'
+            [[ "${allfiles[@]}" != *.opus\ * ]] && printf 'This directory does not contain files in the expected format or filename.\n'
+            [[ "${allfiles[@]}"  = *.opus\ * ]] && printf 'The rudimentarly built-in file renaming was unable to put the opus files into the pattern of <Title> -- Part ##: <Chapter Title>.opus\nPlease rename files and retry indexopus.'
             exit
         fi
-    fi ; }
+     fi
+}
 
 
 ##--> Main Code <--####################################################################################
@@ -619,7 +590,7 @@ if [[ "$overwrite" != false ]] && [[ "$?" != 0 ]]; then
 fi
 
 if [[ ! -f "$tmp/$output" ]]; then
-   printf '\n\n\n%s%sWhere the fuck is %s/%s?\nexit 1' "$tmp/$output"
+   printf '\n\n\n%s%sWhere the fuck is %s/%s?\nexit 1%s' "$red" "$bold" "$tmp" "$output" "$tput0"
    printline "Leaving $scriptname: error, exit 1!"
    exit 1
 fi
