update

diff --git a/indexopus b/indexopus
--- a/indexopus
+++ b/indexopus
@@ -18,11 +18,14 @@
 
 shopt -s extglob nullglob dotglob
 scriptpath=$(realpath "$0")
+scriptname="${scriptpath##*\/}"
 confpath="$HOME/.config/indexopus.conf"
 . "$confpath"                                 #this needs to move.
 . "$HOME/bin/gits/indexopus/indexopus.lib"
 ulon="$(tput smul)"  #underline on
 uloff="$(tput rmul)" #underline off
+iton="$(tput sitm)" #italics on
+itoff="$(tput ritm)" #italics off
 red="$(tput setaf 9)" #red fg
 white="$(tput setaf 15)" #white fg
 tput0="$(tput sgr0)" #reset tput changes
@@ -118,7 +121,7 @@ rmyn(){
 
 gettitle(){
 [[ ! -n "$title" ]] && titles=(*Part\ ??*.opus) && title="${titles[0]% -- Part*}"
-ititle="${ulon}$title${uloff}"
+ititle="${iton}$title${itoff}"
 output="$title -- Audiobook.opus"
 ioutput="$ititle -- Audiobook.opus"
 }
@@ -200,31 +203,16 @@ reindex(){
   if [[ -f "chapters.json" ]] && [[ ! $(grep '{"error":"Chapters not found"}' "chapters.json") ]]; then
     readarray -t chap_titles < <(jq -r '.chapters[] | .title' "chapters.json" 2>/dev/null)
     readarray -t chap_starts < <(jq -r '.chapters[] | .startOffsetMs' "chapters.json" 2>/dev/null)
-#    for ((i=0; i<"${#chap_starts[@]}"; i++));
-#      do
-#        chap_starts[i]=$(echo $(( chap_starts[i] / 1000 )) )
-#      done
-
-#  for ((i=0; i<"${#chap_starts[@]}"; i++)); do
-#    seconds=$(echo "scale=3; ${chap_starts[i]} / 1000" | bc)
-#    chap_starts[i]=$(echo $seconds | perl -nle '/([0-9\.]+)/ && ($t +=$1) && printf "%02d:%02d:%06.03f\n", $t/3600, $t/60%60, $t%60 + $t-int($t)' | tail -n 1)
-#  done
-
   for ((i=0; i<"${#chap_starts[@]}"; i++)); do
     sec=$(( chap_starts[i] / 1000 ))
     ms=$(( chap_starts[i] % 1000 ))
     chap_starts[i]="${sec}.${ms}"
   done
 
-#    pause "$(printf '%s\n' "${chap_starts[@]}")"
-#    pause "$(printf '%s\n' "${chap_titles[@]}")"
-
   else
     readarray -t chap_titles < <(jq -r '.chapters[] | .title' "metadata.json" 2>/dev/null)
     readarray -t chap_starts < <(jq -r '.chapters[] | .start' "metadata.json" 2>/dev/null)
   fi
-
-#pause $(printf '%s - %s\n' "${chap_titles}" "${chap_titles}")
 
  [[ ! "${chap_titles[@]}" ]] || [[ ! "${chap_starts[@]}" ]] &&
     printf 'Error with %s/metadata.json; check and retry.\nexit 1' "$PWD" &&
@@ -332,7 +320,6 @@ writeindex(){
   printf '%sChapter info added...\n%s' "$relipsis" "$tput0"
   printf '%sStripping MP4 tags%s\n%s' "$relipsis" "$relipsis" "$tput0"
   [[ "$rmmatch" != 'true' ]] &&
-#     pause "$(printf '%sStripping MP4 tags%s\n%s' "$relipsis" "$relipsis" "$tput0")"
   mp4grep="$(IFS=\|; echo "${remove_mp4tags[*]}")"
 
 #  This is method one to remove the unwanted mp4 tags:
@@ -392,7 +379,7 @@ writeindex(){
 #              mv "$i" "${i/ -- Part / -- Part $n: Part }"
 #            done
 #        else
-#          printf 'This directory does not contain files in the format of %s<Title>%s -- Part ##:<Chapter Title>.opus\nPlease check the directory this script was launched from to make sure it contains the proper files.\n' "${ulon}" "${uloff}"
+#          printf 'This directory does not contain files in the format of %s<Title>%s -- Part ##:<Chapter Title>.opus\nPlease check the directory this script was launched from to make sure it contains the proper files.\n' "${iton}" "${itoff}"
 #          exit
 #      fi
 #   fi
@@ -498,7 +485,7 @@ else
 ##--> indexopus <--####################################################################################
 
 echo
-printline "${bold}  Welcome to ${white}indexopus  ${tput0}"
+printline "${bold}  Welcome to ${red}indexopus  ${tput0}"
 echo
 
 # Parse command-line options
@@ -582,7 +569,7 @@ gettitle "$title"
 
 if [[ -f ./"$output" ]] && [[ "$rmmatch" != true ]]
  then
-   printf 'This directory already contains %s\n' "$ioutput"
+   printf 'This directory already contains %s\n\n' "$ioutput"
    if confirm "Overwrite the existing file? (y/n) "
     then
       printf '\n%sOverwriting %s -- Audiobook.opus...%s\n' "$relipsis" "$ititle" "${tput0}"
@@ -590,7 +577,8 @@ if [[ -f ./"$output" ]] && [[ "$rmmatch" != true ]]
       [[ -f metadata.json ]] &&
         confirm "$(printf '\nNot overwriting.\nA metadata.json file was found. Would you like to reindex the file?')" &&
         reindex=true && overwrite=false ||
-        exit
+        printf '\n%s\n\n' "$(printline "  Exiting ${scriptname}: ${red}user abort. exit (130)${tput0}  ")"
+        exit 130
    fi
 fi
 
@@ -603,21 +591,24 @@ fi
 
 printf '\n%sGenerating the index for %s -- Audiobook.opus from...%s\n\n' "$relipsis" "$ititle" "$tput0"
 
+rm opusindex opusfiles 2>/dev/null
+
 createindex
 
-####
-#this needs to be reordered around here...  want to get some confirmation we're going to be doing this before we concatinate.
-
-
 printf '%s:~%s~%s\n\n' "${createdindex[@]}"|paste|column -t -s "~"
-printf '%s%sProposed index for %s:%s%s\n' "$red" "$bold" "$reintitle" "${tput0}" "$bold"
-printf '%s .. %s\n' "${rawindex[@]}"
+printf '\n%s%sProposed index for %s:%s%s\n' "$red" "$bold" "$ititle" "${tput0}" "$bold"
 
+printf '%s .. %s\n' "${rawindex[@]}"  # DO NOT touch this line
+echo
 
-[[ "$rmmatch" != "true" ]] && $( confirm "Continue with concatination? (y/Y)/(n/N)" || exit )
+if [[ "$rmmatch" != "true" ]] &&
+   ! $(confirm "Continue with concatination? (y/n) "); then
+   printf '\n\nWell why are you here then?%s\n\n' "$tput0"
+   printline "  ${bold}Leaving ${scriptname}: ${red}User abort. exit (130)  ${tput0}$(echo)"
+   exit 130
+fi
 
-
-printf '\n%sConcatenating %s -- Part ??: *.opus...%s\n\n' "$relipsis" "$ititle" "$tput0"
+printf '\n\n%sConcatenating %s -- Part ??: *.opus...%s\n\n' "$relipsis" "$ititle" "$tput0"
 
 #concatination step:
 dirsize="$(du -csb *Part*opus|tail -n1)"
@@ -625,7 +616,17 @@ dirsize="${dirsize%%$'\t'*}" #remove everything after first tab stop
 dirsize="$((dirsize/1000))"  #convert bytes to KiB
 printf '%sparts=  %sKiB time=%s%s\n' "$red" "$dirsize" "$duration" "$tput0"
 [[ "$overwrite" != false ]] && ffmpeg -nostdin -hide_banner -v error -stats -f concat -safe 0 -thread_queue_size 1024 -i "$tmp/opusfiles" -n -acodec copy "$tmp/$output"
-[[ "$overwrite" != false ]] && [[ "$?" != 0 ]] && echo && echo "ffmpeg failed to concatinate; exit 1" && echo && exit 1
+
+if [[ "$overwrite" != false ]] && [[ "$?" != 0 ]]; then
+  printf "\nffmpeg failed to concatinate; exit 1\n\n" && exit 1
+fi
+
+if [[ ! -f "$tmp/$output" ]]; then
+   printf '\n\n\n%s%sWhere the fuck is %s/%s?\nexit 1' "$tmp/$output"
+   printline "Leaving $scriptname: error, exit 1!"
+   exit 1
+fi
+
 
 printf '\n\n%sIncorporating index into%s %s -- Audiobook.opus%s\n\n%s' "$relipsis" "$white" "$ititle" "$relipsis" "$tput0"
 
diff --git a/m4b2opus b/m4b2opus
--- a/m4b2opus
+++ b/m4b2opus
@@ -6,7 +6,8 @@
 shopt -s nullglob
 
 threads=4
-scriptname=$(realpath "$0")
+scriptpath="$(realpath "$0")"
+scriptname="${scriptpath##*\/}"
 ulon=$(tput smul)  #underline on
 uloff=$(tput rmul) #underline off
 bold="$(tput bold)"  #bold on
@@ -252,7 +253,7 @@ noindexsplit(){
     cd "$convertdir"
     #for i in First Second Third Fourth
     for ((i=1; i<=parts; i++)); do
-      i="$(printf '%02d\n' "$i")"
+      printf -v i '%02d\n' "$i"
       ((n++))
       for f in *\ --\ Part\ 0"$n".*; do
         mv "$f" "${f/./: Part $i.}"
@@ -263,6 +264,7 @@ noindexsplit(){
 ##--> Main Code <--################################################################################
 ##--> m4b2opus <--####################################################################################
 
+echo
 printline "${bold}  Welcome to ${white}$script  ${tput0}"
 
 [[ "$1" == @(edit|e|nano) ]] && editscript
@@ -270,8 +272,6 @@ printline "${bold}  Welcome to ${white}$script  ${tput0}"
 [[ "$1" == "-y" ]] && shift && rmmatch=true
 [[ "$1" == "--stats" ]] && shift && stats=true
 #[[ "$1" ]] && clifile "$1"
-
-#[[ "$rmmatch" ]] && pause "$bold$red$scriptname will overwrite upon matches."
 
 filecheck "$1" && [[ ! "$?" == 0 ]] && exit
 
@@ -301,6 +301,7 @@ if [[ ! "$(mediainfo "$m4bin"|grep Menu)" =~ ^Menu ]]; then  #process unindexed 
 else
   m4bsplit "$m4bin" "$convertdir"
   cd "$convertdir"
+  (( $(ls *m4a|wc -l) > 99 )) && for i in *\ --\ Part\ ??\:\ *.m4a; do mv "$i" "${i/Part /Part 0}"; done
   regexexp='.*\ --\ Part\ [[:digit:]]{2}:\ Chapter\ [[:digit:]][\ |\.]'
     for m4afile in *m4a
       do
@@ -320,13 +321,13 @@ printline "${bold}  Calling external dependency:${red} opus.book.4  ${tput0}"
 #printf '%s\n----------  Calling external dependency: %sopus.book.4%s  ----------\n' "$bold" "$red" "$tput0"
 
 opus.book.4 -d "${m4bindur#*: }"  #this is a dependency; needs to be made a function?
-if (( "$?" > 1 ));  then
-  echo "opus.book.4 failed; exit 1"
-#    exit 1
+if (( "$?" > 0 ));  then
+  printf '%s\n\nopus.book.4 failed; exit 1\n\n%s' "$bold" "$tput0"
+  printline "  Leaving $scriptname: Error!  "
+  exit 1
 fi
 
-#printf '%s\n----------  Leaving external dependency: %sopus.book.4%s  ----------\n' "$bold" "$red" "$tput0"
-printline "${bold}  Leaving external dependency: ${red} opus.book.4  ${tput0}"
+printline "${bold}  Returning from external dependency: ${red} opus.book.4  ${tput0}"
 #opus.book.4##################################################################################
 
 clear -x
@@ -340,14 +341,9 @@ printf '%sDuration of the original m4b file: %s%s%s\n' "$bold" "$red" "$m4bindur
 printf '%sDuration of the .opus part files: %s%s%s\n' "$bold" "$red" "$opuspartdur" "$tput0"
 
 ##indexopus##################################################################################
-# Create a named pipe (FIFO)
-#mkfifo "$convertdir/mypipe"
-
-# Open the FIFO for writing
-#exec 3<> "$convertdir/mypipe"
-
-#printf '\n\n%s----------  Calling external dependency: %sindexopus%s  ----------\n' "$bold" "$red" "$tput0"
+echo
 printline "${bold}  Calling external dependency:${red} indexopus  ${tput0}"
+echo
 
 
 if [[ "$rmmatch" = true ]]
@@ -358,16 +354,13 @@ if [[ "$rmmatch" = true ]]
 fi
    ec4io="$?" 				# error code 4 indexopus
    [[ "$ec4io" = 2 ]] && iorm=true
-   [[ "$ec4io" = 1 ]] && printf 'indexopus exited for some unknown reason with exit 1. investigate.\nexit 1' && exit 1
+   [[ "$ec4io" = 1 ]] && printf 'How the hell did you manage to get here?!' && exit
+   [[ "$ec4io" = 130 ]] && printf '%sindexopus was aborted by user, exit (130). Investigate...\n%s\n%s\n\n' "$bold" "$tput0" "$(printline "  ${bold}Leaving ${scriptname}: ${red}indexopus aborted, exit (1)${tput0}  ")" && exit
 
 
-#printf '\n\n%s----------  Leaving external dependency: %sindexopus%s  ----------\n' "$bold" "$red" "$tput0"
-printline "${bold}  Leaving external dependency:${red} indexopus  ${tput0}"
+printline "${bold}  Returning from external dependency:${red} indexopus  ${tput0}"
 ##indexopus##################################################################################
 
-# Close the FIFO
-#  exec 3>&-
-#  rm "$convertdir/mypipe"
 
 
 tmp="/tmp/indexopus-$stamp"  #this probably doesn't exist...
@@ -379,32 +372,42 @@ titleopus="$title -- Audiobook.opus"
      exit 1
 
 mv "$titleopus" "$swd"
+opusparts=( *opus )
 cd "$swd"
 
-printf '\n%sCleaning up remaining files:%s\n\n' "$red" "$tput0"
-ls "$tmp" "$convertdir/m4a" 2>/dev/null
-checkdur
-#(( $(bc <<< "scale=3; ($var1 - $var2) / $var2 > 0.001") ))
-  if [[ "$rmmatch" = true ]] && (( $(bc <<< "scale=3; ($(sex2sec "$(checkdur m4b)") - $(sex2sec "$(checkdur opus)")) / $(sex2sec "$(checkdur opus)") > 0.001") )); then
+[[ ! "$rmmatch"=true ]] && pause "Need to check to see if $tmp is being created... when indexopus isn't run with -y"
+
+checkdur # probably do something different here since you have m4bindur and have to calc opusdur...
+opusdursec="$(sex2sec "$(checkdur opus)")"
+m4bindursec="$(sex2sec $m4bindur)"
+if [[ "$rmmatch" = true ]] && (( opusdursec > 0 )); then
+  verifydur=$(bc <<< "scale=4; ($m4bindursec - $opusdursec) / $opusdursec " ); verifydur="${verifydur/#-}"
+  verifydur="${verifydur/#-}"
+  if [[ $(bc <<< "scale=4; $verifydur < 0.001") ]]; then
     rm -r *m4b "$convertdir"
-    printf '\n\n%sDone.\n\nPlease see %s/%s%s\n\n' "$relipsis" "$PWD" "$ioutput" "$tput0"
+    [[ "$m4bindursec" != "$opusdursec" ]] &&
+       printf '\n%sDurations don'\''t %sexactly%s match but fuckin'\'' close '\''nuff!%s\n' "$relipsis" "$(tput sitm)" "$(tput ritm)" "$tput0" ||
+      printf '%sDurations match!%s\n' "$relipsis" "$tput0"
+    printf '\n%sDone.\n\nPlease see %s/%s%s\n\n' "$relipsis" "$PWD" "$ioutput" "$tput0"
     exit
-else
-  if [[ "$rmmatch" = true ]] && [[ "$(checkdur m4b)" != "$(checkdur opus)" ]]; then
+  elif [[ "$rmmatch" = true ]] && [[ "$(checkdur m4b)" != "$(checkdur opus)" ]]; then
     printf '%s%sThe m4b and opus audiobook durations do not match!\n' "$bold" "$red"
     printf '%s%sm4b2opus will not automatically delete starting and temporary files!\n' "$white" "$tput0"
     printf '\n\n'
     printf '%s-y/-f specified, but the durations do not match!\n%s' "$bold" "$tput0"
   fi
+fi
+
+  printf '\n%sCleaning up remaining files:%s\n\n' "$red" "$tput0"
+#  ls "$tmp" "$convertdir" 2>/dev/null
 
   printf '\n\n'
 # the 2>/dev/null does not work for rmyn -- rewrite!!
 #  rmyn -q "${red}${bold}Remove the conversion ./m4a directory? ${tput0}" "${red}...Leaving ./m4a.${tput0}" rm -r "$convertdir/m4a"
-  [[ ! "$iorm" ]] && rmyn -q "${red}${bold}Remove $ititle -- Part *.opus files? ${tput0}" "${red}...Leaving $ititle -- Part *.opus files...${tput0}" rm "$convertdir/$title"\ --\ Part\ ??:*.opus
+  [[ ! "$iorm" ]] && [[ "$opusparts" ]] && rmyn -q "${red}${bold}Remove $ititle -- Part *.opus files? ${tput0}" "${red}...Leaving $ititle -- Part *.opus files...${tput0}" rm "$convertdir/$title"\ --\ Part\ ??:*.opus
   rmyn "${red}${bold}Remove the starting $m4bin? " "${red}Leaving starting $m4bin${tput0}" rm "$m4bin"
-  for i in *m4b "$convertdir" .tmp* "$tmp"; do [[ -a "$i" ]] && fnrmr "$i"; done
+  for i in "$convertdir" .tmp* "$tmp"; do [[ -a "$i" ]] && fnrmr "$i"; done
   printf '\n\n...Done.\n\nPlease see %s/%s\n\n' "$PWD" "$ioutput"
-fi
 
 printline "${bold}  Exiting (0) ${white}m4b2opus  ${tput0}"
 exit 0
