update

diff --git a/indexopus b/indexopus
--- a/indexopus
+++ b/indexopus
@@ -30,6 +30,7 @@ bold="$(tput bold)" #bold on
 relipsis="$red..."
 stamp="$(date +%s)"  #sets datecode for all of indexopus - could use info from m4b2opus later
 tmp="/tmp/indexopus-$stamp" #this could change based on info from m4b2opus
+remove_mp4tags=("major_brand" "minor_version" "compatible_brands" "encoded_by" 'OverDrive\ MediaMarkers' "handler_name" "vendor_id")
 
 editscript(){
   local script path; script="${scriptpath##*/}"; path="${scriptpath%/*}"; swp="$path/.$script.swp"
@@ -136,13 +137,17 @@ createindex(){
         createdindex+=( "$i" )
         createdindex+=( "$(printf 'CHAPTER%03d=%s' "$chno" "$ts")" )
         createdindex+=( "$(printf 'CHAPTER%03dNAME=%s' "$chno" "$chna")" )
-      else
+        rawindex+=( "$ts" )
+        rawindex+=( "$chna" )
+     else
         ts="00:00:00.000"
         printf 'CHAPTER%03d=%s\n' "$chno" "$ts" >> "$tmp/opusindex"
         printf 'CHAPTER%03dNAME=%s\n' "$chno" "$chna" >>  "$tmp/opusindex"
         createdindex+=( "$i" )
         createdindex+=( "$(printf 'CHAPTER%03d=%s' "$chno" "$ts")" )
         createdindex+=( "$(printf 'CHAPTER%03dNAME=%s' "$chno" "$chna")" )
+        rawindex+=( "$ts" )
+        rawindex+=( "$chna" )
       fi
       d=$(ffprobe -v error -show_entries format=duration -of default=nk=1:nw=1 "$i")
 #     d=$(mplayer -vo dummy -ao dummy -identify "$i" 2>/dev/null | perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "$t"' | tail -n 1)
@@ -176,6 +181,11 @@ reindex(){
   local t chap_title chap_starts reintitle
   t=0
   chno=0
+  itemid_pwd(){
+    local itempwd="${1:-"${PWD}"}}"
+    sqlitepwd="${PWD//\'/\'\'}"
+   }
+
 
   if [[ ! -f "chapters.json" ]]; then
     if confirm "${bold}No chapters.json; retrieve chapter info from the web?${tput0}"; then
@@ -258,8 +268,8 @@ reindex(){
   printf '%s%sProposed index for %s:%s%s\n' "$red" "$bold" "$reintitle" "${tput0}" "$bold"
   printf '%s\t\t\t\t : %s\n' "${rawindex[@]}"
 # printf '%s                             : %s\n' "${rawindex[@]}"
-  sqlitepwd="${PWD//\'/\'\'}"
-  itemid="$(sqlite3 "$abssqlite" "select id FROM libraryitems WHERE path=='$sqlitepwd';" ".exit")"
+  itemid_pwd
+  itemid="$(sqlite3 "$abssqlite" "select id FROM libraryitems WHERE path=='$sqlitepwd';")"
   printf '%s\n%sThis index was generated from existing %s;\n' "$tput0" "$relipsis" "$jsonfile"
   [[ "$itemid" ]] && printf '...look up new chapter information at\ngoogle-chrome %s/audiobook/%s/chapters\n\n\n' "$absserver" "$itemid"
   [[ ! "$itemid" ]] && printf '%s%s not found in absdatabase.sqlite!%s\n%sCheck path and metadata.json file\n\n\n' "$bold" "$PWD" "$tput0" "$red"
@@ -287,14 +297,17 @@ reindex(){
   rm -rf "$tmp"
 
 }
+
 ##reindex()####################################################################################
 
 writeindex(){
-  local output="$1" mp4tags mp4grep mp4opustags chaptag tags ck4tags args
-
+  local output="$1" mp4grep mp4opustags chaptag tags ck4tags args
+  [[ ! "$remove_mp4tags" ]] &&
+     remove_mp4tags=("major_brand" "minor_version" "compatible_brands" "encoded_by" "OverDrive MediaMarkers")
+#this works, why won't it work in the array?
+# opustags -d "OverDrive MediaMarkers" -i "$output"
   if [[ "$(opustags "$output")" = *CHAPTER* ]]
     then
-      opustags -d "OverDrive MediaMarkers" -i "$output"
       printf '\n%s%s%s contains existing tags; removing...%s\n' "$relipsis" "$bold" "$title" "$tput0"
       tags=( $(opustags "$output") )
       tags=( $(printf -- '-d%s\n' "${tags[@]%=*}"|\grep CHAPTER|sort -u) )
@@ -318,13 +331,167 @@ writeindex(){
   opustags -i "$output" "${args[@]}"
   printf '%sChapter info added...\n%s' "$relipsis" "$tput0"
   printf '%sStripping MP4 tags%s\n%s' "$relipsis" "$relipsis" "$tput0"
-  mp4tags=("major_brand" "minor_version" "compatible_brands" "encoded_by" "OverDrive MediaMarkers")
-  mp4grep="$(IFS=\|; echo "${mp4tags[*]}")"
-# mp4opustags="$(printf -- '-d %s ' "${mp4tags[@]}")"
-  mp4opustags=( "$(printf -- '-d %s ' "${mp4tags[@]}")" )
-  [[ $(opustags "$output" |grep -E "$mp4grep" ) ]] && opustags -i "$output" "${mp4opustags[@]}"
+  [[ "$rmmatch" != 'true' ]] &&
+#     pause "$(printf '%sStripping MP4 tags%s\n%s' "$relipsis" "$relipsis" "$tput0")"
+  mp4grep="$(IFS=\|; echo "${remove_mp4tags[*]}")"
+
+#  This is method one to remove the unwanted mp4 tags:
+  readarray -t mp4opustags -- < <(printf -- '-d\n%s\n' "${remove_mp4tags[@]}")
+  mp4opustags+=(-i "$output")
+  [[ $( opustags "$output" |grep -E "$mp4grep" ) ]] && opustags "${mp4opustags[@]}"
+
+#  This is method two to remove the unwanted mp4 tags...
+#  Both of them work, but I couldn't get the first one to work so I wrote this one
+#  Keeping for reference for a while since this is such a fucking pain in the ass.
+
+  if [[ $( opustags "$output" |grep -E "$mp4grep" ) ]]; then
+    for i in "${remove_mp4tags[@]}"; do
+      mp4args+=(-d "$i")
+    done
+
+    mp4args+=(-i "$output")    # Should I also use readarray here?  difference?
+    opustags "${args[@]}"
+  fi
+
 }
+
 ##--> writeindex() <--#################################################################################
+
+
+#rename() {
+#   if compgen -G @(*\ --\ Chapter\ ??*.opus|*\ --\ Disc\ ??.opus|*-Part??.opus) &> /dev/null
+#     then
+#       for renopus in *Chapter\ ??*.opus; do [[ -f "$renopus" ]] && mv "$renopus" "${renopus/ Chapter / Part }"; done
+#       for renopus in *Disc\ ??.opus; do [[ -f "$renopus" ]] && mv "$renopus" "${renopus/ Disc / Part }"; done
+#       for renopus in *-Part??.opus; do [[ -f "$renopus" ]] && mv "$renopus" "${renopus/-Part/ -- Part 00: Part }"; done
+#   else
+#     ext=opus
+#
+#     if [[ "$rmmatch" != true ]]; then
+#       confirm "Continue with proposed rename?" &&
+#       for i in *\ -\ ??.opus *\ -\ ???.opus; do mv "$i" "${i/ - / -- Part }"; done ||
+#       exit  # Exit on fail
+#     else
+#       for i in *\ -\ ??.opus *\ -\ ???.opus; do mv "$i" "${i/ - / -- Part }"; done ||
+#       exit  # Exit on fail
+#     fi
+#
+##     if [[ "${opusarray[@]}" =~ '^(.+ - \d{2}\.opus)$' ]]; then
+# #  fi
+#   fi
+#  renopus=( *\ --\ Part\ *.opus )
+#
+##  if [[ "${renopus[0]}" != @(*\ --\ Part\ ???\:\ *.opus|*\ --\ Part\ ??\:\ *.opus) ]]
+#  if ! compgen -G @(*\ --\ Part\ ???\:\ *.opus|*\ --\ Part\ ??\:\ *.opus) &> /dev/null
+#    then
+#      if [[ "${renopus[0]/ -- Part / -- Part 00: Part }" == *\ --\ Part\ ??\:\ *.opus ]]
+#        then
+#          for i in *opus
+#            do
+#              n="${i#* -- Part }"; n="${n%%.opus}"
+#              mv "$i" "${i/ -- Part / -- Part $n: Part }"
+#            done
+#        else
+#          printf 'This directory does not contain files in the format of %s<Title>%s -- Part ##:<Chapter Title>.opus\nPlease check the directory this script was launched from to make sure it contains the proper files.\n' "${ulon}" "${uloff}"
+#          exit
+#      fi
+#   fi
+#
+#}
+rename() {
+ext=opus #local?
+
+if [[ "${opusarray[@]}" =  *\ --\ @(Chapter|Part|Disc)\ @(??|???).opus* ]]; then
+    declare -A confirm_rename
+    for i in "${opusarray[@]}"; do
+        n="${i%.opus}"; n="${n##* }"
+        title="${i% -- *}"
+        order="${i##* -- }"
+        newname="${i/ -- @(Part|Chapter|Disc) / -- Part $n: Part }"
+        # Display the proposed rename
+        confirm_rename["$i"]="$newname"
+        printf '%s    %s---->%s    %s%s\n%s' "$i" "$bold" "$tput0" "$red" "$newname" "$tput0"
+    done
+    echo
+
+    # Confirm the rename
+    [[ ! "$rmmatch" ]] && confirm "${bold}Continue with Proposed Rename? (Y/N)/(y/n) " &&
+    for i in "${!confirm_rename[@]}"; do
+        [[ "$i" = *\ @(Chapter|Disc)\ @(??|???).opus ]] &&
+        mv "$i" "${confirm_rename["$i"]}"
+    done
+
+#  if [[ "${opusarray[@]}" =  *\ --\ @(Chapter|Part|Disc)\ @(??|???).opus* ]]; then
+#    for i in "${opusarray[@]}"; do
+#      n="${i%.opus}"; n="${n##* }"
+#
+#      [[ "$i" = *\ @(Part|Chapter|Disc)\ @(??|???).opus ]] &&
+#        newname="${i/ @(Part|Chapter|Disc) / Part $n: Part }"
+#          printf '%s    %s---->%s    %s%s\n%s' "$i" "$bold" "$tput0" "$red" "$newname" "$tput0"
+#    done
+#          echo
+#     confirm "${bold}Continue with Proposed Rename" &&
+#        for i in *\ @(Part|Chapter|Disc)\ @(??|???).opus; do
+#          n="${i%.opus}"; n="${n##* }"
+#          [[ "$i" = *\ @(Chapter|Disc)\ @(??|???).opus ]] &&
+#            mv "$i" "${i/ @(Chapter|Disc) / Part $n: Part }"
+#        done
+
+  elif [[ "${opusarray[@]}" = *-Part@(??|???).opus ]]; then
+    for i in *-Part??.opus; do
+      n="${i%.opus}"; n="${n##*-Part}"
+          newname="${i/-Part/ -- Part $n: Part }"
+          printf '%s    %s---->%s    %s%s\n%s' "$i" "$bold" "$tput0" "$red" "$newname" "$tput0"
+    done
+      echo
+      [[ ! "$rmmatch" ]] && confirm "${bold}Continue with Proposed Rename" &&
+      for i in *-Part??.opus; do
+        n="${i%.opus}"; n="${n##*-Part}"
+        [[ "$i" = *\ @(Chapter|Disc)\ @(??|???).opus ]] &&
+          mv "$i" "${i/-Part/ -- Part $n: Part }"
+       done
+else
+    regex=".+[[:space:]]-[[:space:]][[:digit:]]{1,3}\.opus"
+      for i in *\ -\ @(?|??|???).opus; do
+        if [[ -f "$i" && "${opusarray[@]}" =~ $regex ]]; then
+          n="${i%.opus}"; n="${n##* - }"
+          newname="${i/ - / -- Part $n: Part }"
+          printf '%s    %s---->%s    %s%s\n%s' "$i" "$bold" "$tput0" "$red" "$newname" "$tput0"
+        fi
+      done
+      for i in *\ -\ @(?|??|???).opus; do
+        if [[ "$rmmatch" != true ]]; then
+            # Ask for confirmation before renaming
+            echo
+            [[ "$rmmatch" ]] && confirm "Continue with proposed rename?" &&
+            for opusfile in *"$ext"; do
+                [[ -f "$opusfile" ]] && mv "$opusfile" "${opusfile/ - / -- Part }"
+            done ||
+            exit
+        else
+            for opusfile in *"$ext"; do
+                [[ -f "$opusfile" ]] && mv "$opusfile" "${opusfile/ - / -- Part }"
+            done ||
+            exit
+        fi
+      done
+    fi
+
+    # Check if files match the expected naming pattern after renaming
+    renopus=( *\ --\ Part\ *.opus )
+    if ! compgen -G '@(*\ --\ Part\ ???\:\ *.opus|*\ --\ Part\ ??\:\ *.opus)' &> /dev/null; then
+        # If files do not match expected naming pattern, attempt to rename them
+        if [[ "${renopus[0]/ -- Part / -- Part 00: Part }" == *\ --\ Part\ ??\:\ *.opus ]]; then
+            for opusfile in *opus; do
+                n="${opusfile#* -- Part }"; n="${n%%.opus}"
+                mv "$opusfile" "${opusfile/ -- Part / -- Part $n: Part }"
+            done
+        else
+            # Exit if files do not match expected naming pattern and cannot be renamed
+            printf 'This directory does not contain files in the expected format.\n'
+            exit
+        fi
+    fi ; }
 
 
 ##--> Main Code <--####################################################################################
@@ -401,40 +568,12 @@ if [[ -f metadata.json ]] && [[ "$(jq -r '.chapters[0].title' metadata.json)" ]]
       reindex=true
 fi
 
-if ! compgen -G @(*\ --\ Part\ ???\:\ *.opus|*\ --\ Part\ ??\:\ *.opus) &> /dev/null
+if ! compgen -G *\ --\ Part\ @(??|???)\:\ *.opus &> /dev/null
  then
-   if compgen -G @(*\ --\ Chapter\ ??*.opus|*\ --\ Disc\ ??.opus|*-Part??.opus) &> /dev/null
-     then
-       for renopus in *Chapter\ ??*.opus; do [[ -f "$renopus" ]] && mv "$renopus" "${renopus/ Chapter / Part }"; done
-       for renopus in *Disc\ ??.opus; do [[ -f "$renopus" ]] && mv "$renopus" "${renopus/ Disc / Part }"; done
-       for renopus in *-Part??.opus; do [[ -f "$renopus" ]] && mv "$renopus" "${renopus/-Part/ -- Part 00: Part }"; done
-   fi
 
-pause "$(printf '%s\n' "${opusarray[@]}")"
 
-if [[ "${opusarray[@]}" =~ '^(.+ - \d{2}\.opus)$' ]]; then
- for renopus in *\ -\ {?..???}.opus; do
-  mv "$renopus" "${renopus/ - / -- Part 00: Part }"
- done
-fi
+ rename
 
-   renopus=( *\ --\ Part\ *.opus )
-
-#  if [[ "${renopus[0]}" != @(*\ --\ Part\ ???\:\ *.opus|*\ --\ Part\ ??\:\ *.opus) ]]
-   if ! compgen -G @(*\ --\ Part\ ???\:\ *.opus|*\ --\ Part\ ??\:\ *.opus) &> /dev/null
-     then
-       if [[ "${renopus[0]/ -- Part / -- Part 00: Part }" == *\ --\ Part\ ??\:\ *.opus ]]
-         then
-           for i in *opus
-             do
-               n="${i#* -- Part }"; n="${n%%.opus}"
-               mv "$i" "${i/ -- Part / -- Part $n: Part }"
-             done
-         else
-           printf 'This directory does not contain files in the format of %s<Title>%s -- Part ##:<Chapter Title>.opus\nPlease check the directory this script was launched from to make sure it contains the proper files.\n' "${ulon}" "${uloff}"
-           exit
-       fi
-   fi
 fi
 
 d=0
@@ -465,20 +604,32 @@ fi
 printf '\n%sGenerating the index for %s -- Audiobook.opus from...%s\n\n' "$relipsis" "$ititle" "$tput0"
 
 createindex
+
+####
+#this needs to be reordered around here...  want to get some confirmation we're going to be doing this before we concatinate.
+
+
 printf '%s:~%s~%s\n\n' "${createdindex[@]}"|paste|column -t -s "~"
+printf '%s%sProposed index for %s:%s%s\n' "$red" "$bold" "$reintitle" "${tput0}" "$bold"
+printf '%s .. %s\n' "${rawindex[@]}"
+
+
+[[ "$rmmatch" != "true" ]] && $( confirm "Continue with concatination? (y/Y)/(n/N)" || exit )
+
+
 printf '\n%sConcatenating %s -- Part ??: *.opus...%s\n\n' "$relipsis" "$ititle" "$tput0"
 
 #concatination step:
 dirsize="$(du -csb *Part*opus|tail -n1)"
 dirsize="${dirsize%%$'\t'*}" #remove everything after first tab stop
-dirsize="$((dirsize/1000))" #convert bytes to KiB
+dirsize="$((dirsize/1000))"  #convert bytes to KiB
 printf '%sparts=  %sKiB time=%s%s\n' "$red" "$dirsize" "$duration" "$tput0"
-[[ "$overwrite" != false ]] && ffmpeg -nostdin -hide_banner -v error -stats -f concat -safe 0 -thread_queue_size 1024 -i "$tmp/opusfiles" -n -acodec copy "/tmp/$output"
+[[ "$overwrite" != false ]] && ffmpeg -nostdin -hide_banner -v error -stats -f concat -safe 0 -thread_queue_size 1024 -i "$tmp/opusfiles" -n -acodec copy "$tmp/$output"
 [[ "$overwrite" != false ]] && [[ "$?" != 0 ]] && echo && echo "ffmpeg failed to concatinate; exit 1" && echo && exit 1
 
 printf '\n\n%sIncorporating index into%s %s -- Audiobook.opus%s\n\n%s' "$relipsis" "$white" "$ititle" "$relipsis" "$tput0"
 
-mv "/tmp/$output" "$output"
+mv "$tmp/$output" "$output"
 
 writeindex "$output"
 
@@ -508,7 +659,7 @@ else
   exit 1
 fi
 
-if [[ "$rmmatch" && "$duration" = "$outdur" ]]; then
+if [[ "$rmmatch" = true && "$duration" = "$outdur" ]]; then
   printf '%sDurations of part and indexed opus files match, automatically deleting temporary files!\n\nPlease see %s%s%s/%s%s\n\n%sDone.\n\n%s' "$relipsis" "$white" "$bold" "$PWD" "$ioutput" "$tput0" "$relipsis" "$tput0"
   rm -r "$title"\ --\ Part\ *.opus "$tmp"/opus@(files|index)
   printline "${bold}  Exiting (0) ${white}indexopus  ${tput0}"
@@ -518,7 +669,9 @@ fi
 [[ "$reindex" = true ]] && confirm "$(printf '%sA metadata.json file was found!\n%sReindex the file with audiobookshelf chapter info?%s' "${red}" "${bold}" "${tput0}")" && indexopus reindex
 
 #this isnt working right tonight and it is late.
-[[ "$reindex" != true ]] && rmyn "${bold}${red}Remove $title -- Part *.opus & temp files? (y/n) ${tput0}" "$bold Leaving temporary files $tput0" rm -r "$title"\ --\ Part\ *.opus "$tmp"/opus@(files|index) && iorm=true ||
+#this was "$reindex" != true...  changing to "$rmmatch":
+#[[ "$reindex" != true ]] && rmyn "${bold}${red}Remove $title -- Part *.opus & temp files? (y/n) ${tput0}" "$bold Leaving temporary files $tput0" rm -r "$title"\ --\ Part\ *.opus "$tmp"/opus@(files|index) && iorm=true ||
+[[ "$rmmatch" != true ]] && rmyn "${bold}${red}Remove $title -- Part *.opus & temp files? (y/n) ${tput0}" "$bold Leaving temporary files $tput0" rm -r "$title"\ --\ Part\ *.opus "$tmp"/opus@(files|index) && iorm=true ||
  rm -r "$title"\ --\ Part\ *.opus "$tmp"/opus@(files|index)
 
 printf '\n\n%sDone.\n\nPlease see %s%s%s/%s\n\n' "$relipsis" "$white" "$bold" "$PWD" "$ioutput"
diff --git a/m4b2opus b/m4b2opus
--- a/m4b2opus
+++ b/m4b2opus
@@ -22,7 +22,6 @@ stamp="$(date +%s)"
 ## printline()
 ## pause()
 ## checkdur()
-
 . $HOME/bin/gits/indexopus/indexopus.lib
 
 fnrmr(){
@@ -128,17 +127,38 @@ filecheck(){
 ##--> filecheck() <--#################################################################################
 
 calctime(){
-duration=$(find -type f -name "$1" -print0 |
-xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null |
-perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d:%02d:%02d\n",$t/3600,$t/60%60,$t%60' |
-tail -n 1)
- hours=$(find -type f -name "$1" -print0 | xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null | perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d\n",$t/3600' | tail -n 1)
- minutes=$(find -type f -name "$1" -print0 | xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null | perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d\n",$t/60%60' | tail -n 1)
- seconds=$(find -type f -name "*$1" -print0 | xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null | perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d\n",$t%60' | tail -n 1)
+  duration=$(find -type f -name "$1" -print0 |
+			xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null |
+			perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d:%02d:%02d\n",$t/3600,$t/60%60,$t%60' |
+			tail -n 1)
+  hours=$(find -type f -name "$1" -print0 |
+			xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null |
+			perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d\n",$t/3600' |
+			tail -n 1)
+  minutes=$(find -type f -name "$1" -print0 |
+			xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null |
+			perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d\n",$t/60%60' |
+			tail -n 1)
+  seconds=$(find -type f -name "*$1" -print0 |
+			xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null |
+			perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d\n",$t%60' |
+			tail -n 1)
 
- [[ "$hours" =~ "0*(.*)" ]] && hours=${BASH_REMATCH[1]}
- [[ "$minutes" =~ "0*(.*)" ]] && minutes=${BASH_REMATCH[1]}
- [[ "$seconds" =~ "0*(.*)" ]] && seconds=${BASH_REMATCH[1]}
+  [[ "$hours" =~ "0*(.*)" ]] && hours=${BASH_REMATCH[1]}
+  [[ "$minutes" =~ "0*(.*)" ]] && minutes=${BASH_REMATCH[1]}
+  [[ "$seconds" =~ "0*(.*)" ]] && seconds=${BASH_REMATCH[1]}
+
+#BASH_REMATCH is an array variable in Bash that contains the results of the most recent pattern match operation performed using the =~ operator with the [[ ... ]] conditional expression.
+#
+#When you use =~ to match a pattern against a string, Bash populates the BASH_REMATCH array with the text that matches the pattern. The first element (BASH_REMATCH[0]) contains the portion of the string that matches the entire regular expression, while subsequent elements (BASH_REMATCH[1], BASH_REMATCH[2], etc.) contain the portions of the string that match the corresponding capture groups in the regular expression.
+#
+#Here's a breakdown of how BASH_REMATCH is populated:
+#
+#BASH_REMATCH[0]: Contains the portion of the string that matches the entire regular expression.
+#BASH_REMATCH[1]: Contains the portion of the string that matches the first capture group ( ... ).
+#BASH_REMATCH[2]: Contains the portion of the string that matches the second capture group ( ... ), if present.
+#and so on...
+#In the script provided earlier, we used BASH_REMATCH[1] to extract the content inside double quotes. If the pattern \"(.*)\" matches successfully, the content inside the double quotes is captured and stored in BASH_REMATCH[1].
 
 # printf "Duration %s\n" "$duration"
 
@@ -196,28 +216,6 @@ done
 }
 ##--> m4bsplit() <--##################################################################################
 
-#moved to indexopus.lib
-#checkdur(){
-#  local m4a m4b opus
-#  m4a=(*m4a)
-#  m4b=(*m4b)
-#  opus=(*opus)
-#
-#if [[ "$1" ]]
-#  then
-#      find -type f -iname "*.$1" -print0 | xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null | perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d:%02d:%02d\n",$t/3600,$t/60%60,$t%60' | tail -n 1
-#  else
-#    printf '\n%sDuration(s):%s\n' "$bold" "$tput0"
-#    [[ "${#m4a[@]}" -gt 0 ]] &&
-#      printf '%s %s%s%s %s%s\n' "$bold" "$red" "$(    find -type f -iname "*.m4a" -print0 | xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null | perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d:%02d:%02d\n",$t/3600,$t/60%60,$t%60' | tail -n 1)" "$white"  "${m4a[@]}" "$tput0"
-#    [[ "${#m4b[@]}" -gt 0 ]] &&
-#      printf '%s %s%s%s %s%s\n' "$bold" "$red" "$(    find -type f -iname "*.m4b" -print0 | xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null | perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d:%02d:%02d\n",$t/3600,$t/60%60,$t%60' | tail -n 1)" "$white" "${m4b[@]}" "$tput0"
-#    [[ "${#opus[@]}" -gt 0 ]] &&
-#      printf '%s %s%s%s %s%s\n' "$bold" "$red" "$(    find -type f -iname "*.opus" -print0 | xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null | perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d:%02d:%02d\n",$t/3600,$t/60%60,$t%60' | tail -n 1)" "$white" "${opus[@]}" "$tput0"
-# fi
-#}
-##--> checkdur() <--##################################################################################
-
 rmyn(){
  local quiet
  [[ "$1" = '-q' ]] && quiet=true && shift
@@ -244,8 +242,8 @@ noindexsplit(){
   local i n partno m4bin="$1" convertdir="$2"
   printf '%s%sNo index found in %s!\n...%s%sThe item will be spiit into %s parts for efficient ffmpeg conversion.\n...Reindex later with chapter information pulled from the web.\n\n' "$relipsis" "$bold" "$m4bin" "$tput0" "$red" "$partno"
     partno=1
-#    calctime "$m4bin"  #why?  i think this is the only call to calctime?  there's no need for it here...
-
+    calctime "$m4bin"  #why?  i think this is the only call to calctime?  there's no need for it here...
+                       #oh contrare! this is what provides $divsec and the script fails without that line!
     for ((partno=1; partno < $(( threads + 1)); partno++ )); do
        printf '%s%s: %s' "$relipsis" "$partno" "$tput0"
        ffmpeg -n -nostdin -hide_banner -stats -v error -ss $(python -c "print(($partno-1)*$divsec)") -to $(python -c "print($partno*$divsec)") -i "$m4bin" -vn -acodec copy "$convertdir/${m4bin%% -- *} -- Part 0$partno.m4a"
@@ -264,13 +262,16 @@ noindexsplit(){
 
 ##--> Main Code <--################################################################################
 ##--> m4b2opus <--####################################################################################
-printline "${bold}  Welcome to ${white}m4b2opus  ${tput0}"
+
+printline "${bold}  Welcome to ${white}$script  ${tput0}"
 
 [[ "$1" == @(edit|e|nano) ]] && editscript
 
 [[ "$1" == "-y" ]] && shift && rmmatch=true
 [[ "$1" == "--stats" ]] && shift && stats=true
 #[[ "$1" ]] && clifile "$1"
+
+#[[ "$rmmatch" ]] && pause "$bold$red$scriptname will overwrite upon matches."
 
 filecheck "$1" && [[ ! "$?" == 0 ]] && exit
 
@@ -318,7 +319,6 @@ echo
 printline "${bold}  Calling external dependency:${red} opus.book.4  ${tput0}"
 #printf '%s\n----------  Calling external dependency: %sopus.book.4%s  ----------\n' "$bold" "$red" "$tput0"
 
-pause "opus.book.4 -d "${m4bindur#*: }"  #this is a dependency; needs to be made a function?"
 opus.book.4 -d "${m4bindur#*: }"  #this is a dependency; needs to be made a function?
 if (( "$?" > 1 ));  then
   echo "opus.book.4 failed; exit 1"
@@ -330,8 +330,9 @@ printline "${bold}  Leaving external dependency: ${red} opus.book.4  ${tput0}"
 #opus.book.4##################################################################################
 
 clear -x
-[[ ! -d "$convertdir/m4a" ]] && mkdir "$convertdir/m4a"
-mv *.m4a ./m4a
+#need to renable rmyn below if these are uncommented
+#[[ ! -d "$convertdir/m4a" ]] && mkdir "$convertdir/m4a"
+#mv *.m4a ./m4a
 opuspartdur="$(checkdur opus)"
 m4bindur="${m4bindur#*: }"
 
@@ -372,17 +373,22 @@ printline "${bold}  Leaving external dependency:${red} indexopus  ${tput0}"
 tmp="/tmp/indexopus-$stamp"  #this probably doesn't exist...
 titleopus="$title -- Audiobook.opus"
 
-[[ ! -f "$titleopus" ]] && printf '%s%sWhere the fuck is %s?! Exiting (1)\n%s' "$bold" "$red" "$titleopus" "$tput0" && exit 1
+[[ ! -f "$titleopus" ]] &&
+   printf '%s%sError: Where the fuck is %s?! Exiting (1)\n%s' "$bold" "$red" "$titleopus" "$tput0" &&
+     printline "$scriptname" &&
+     exit 1
+
 mv "$titleopus" "$swd"
 cd "$swd"
 
 printf '\n%sCleaning up remaining files:%s\n\n' "$red" "$tput0"
 ls "$tmp" "$convertdir/m4a" 2>/dev/null
 checkdur
-
-if [[ "$rmmatch" = true ]] && [[ "$(checkdur m4b)" = "$(checkdur opus)" ]]; then
-  rm -r *m4b "$convertdir"
-  printf '\n\n%sDone.\n\nPlease see %s/%s%s\n\n' "$relipsis" "$PWD" "$ioutput" "$tput0"
+#(( $(bc <<< "scale=3; ($var1 - $var2) / $var2 > 0.001") ))
+  if [[ "$rmmatch" = true ]] && (( $(bc <<< "scale=3; ($(sex2sec "$(checkdur m4b)") - $(sex2sec "$(checkdur opus)")) / $(sex2sec "$(checkdur opus)") > 0.001") )); then
+    rm -r *m4b "$convertdir"
+    printf '\n\n%sDone.\n\nPlease see %s/%s%s\n\n' "$relipsis" "$PWD" "$ioutput" "$tput0"
+    exit
 else
   if [[ "$rmmatch" = true ]] && [[ "$(checkdur m4b)" != "$(checkdur opus)" ]]; then
     printf '%s%sThe m4b and opus audiobook durations do not match!\n' "$bold" "$red"
@@ -393,7 +399,7 @@ else
 
   printf '\n\n'
 # the 2>/dev/null does not work for rmyn -- rewrite!!
-  rmyn -q "${red}${bold}Remove the conversion ./m4a directory? ${tput0}" "${red}...Leaving ./m4a.${tput0}" rm -r "$convertdir/m4a"
+#  rmyn -q "${red}${bold}Remove the conversion ./m4a directory? ${tput0}" "${red}...Leaving ./m4a.${tput0}" rm -r "$convertdir/m4a"
   [[ ! "$iorm" ]] && rmyn -q "${red}${bold}Remove $ititle -- Part *.opus files? ${tput0}" "${red}...Leaving $ititle -- Part *.opus files...${tput0}" rm "$convertdir/$title"\ --\ Part\ ??:*.opus
   rmyn "${red}${bold}Remove the starting $m4bin? " "${red}Leaving starting $m4bin${tput0}" rm "$m4bin"
   for i in *m4b "$convertdir" .tmp* "$tmp"; do [[ -a "$i" ]] && fnrmr "$i"; done
