update

diff --git a/m4b2opus-4 b/m4b2opus-4
--- a/m4b2opus-4
+++ b/m4b2opus-4
@@ -646,15 +646,20 @@ printf ' %s%s%s\n' "$boldred" "$m4bindur" "$tput0"
 (( verbose )) && printf '[verbose] $title: %s\n' "$title"
 ititle="$iton$title$itoff"
 swd="$(pwd)"
-convertdir="$CACHE/m4b2opus-$title"
+#convertdir="$CACHE/m4b2opus-$title"
+#
+#[[ "$convertdir" = *\'* ]] && convertdir="${convertdir//\'}"  #check $convertdir for \'s and remove them
+#(( verbose )) && pause "[verbose] \$convertidr: $convertdir"
+#
+#if [[ ! -d "$convertdir" ]]; then
+#  mkdir -p "$convertdir" ||
+#  { printf '%s[ERROR]%s Could not create "%s"; please investigate.\n(exit 1)\n%s' "$boldred" "$white" "$convertdir" "$tput0"; exit 1; }
+#fi
 
-[[ "$convertdir" = *\'* ]] && convertdir="${convertdir//\'}"  #check $convertdir for \'s and remove them
-(( verbose )) && pause "[verbose] \$convertidr: $convertdir"
-
-if [[ ! -d "$convertdir" ]]; then
-  mkdir -p "$convertdir" ||
-  { printf '%s[ERROR]%s Could not create "%s"; please investigate.\n(exit 1)\n%s' "$boldred" "$white" "$convertdir" "$tput0"; exit 1; }
-fi
+## probably here to remove \'s for ffmpeg but not sure:
+convertdir="$(mktemp --directory --tmpdir="$CACHE" "m4b2opus-${title//\'}-XXXXXX")" ||
+  { printf 'Failed to create temporary directory for %s. Investigate\n(exit 1)\n\n' "$0"; exit 1; }
+(( verbose )) && pause "[verbose] \$convertdir: $convertdir"
 
 #(( sleepon )) && { printf '\nSleeping for %s%s%s per cli flag...\n' "$boldred" "$sleepdur" "$tput0"; sleep "$sleepdur"; }
 (( sleepon )) && { printf '\nSleeping for %s%s%s per cli flag...\n' "$boldred" "$sleepdur" "$tput0"; sleepfn --countdown; }
