update

diff --git a/mp32opus-1 b/mp32opus-1
--- a/mp32opus-1
+++ b/mp32opus-1
@@ -24,12 +24,21 @@ sourcefn -l /usr/local/bin/indexopus.lib -f sex2sec -f printline -f confirm
 
 filecheck(){
 (( verbose )) && printf '[verbose] Entering filecheck().\n'
-  local clifilename clipath startm4a mvoutput mvec  ## not sure what to do here.  need to see the scope of these variables.
-  [[ -e "$1" ]] && clifilename="$(realpath "$1")"  #if a filename is passed via the cli.  this doesn't work anymore now with -t??
-(( verbose )) && read -rp "[verbose] \$clifilename: ${clifilename:-null}"
-  [[ -d "$clifilename" ]] && clipath="${clifilename%/}" && cd "$clipath" && unset clifilename
-  [[ -f "$clifilename" ]] && clipath="${clifilename%/*}" && cd "$clipath" && clifilename="${clifilename##*/}" ## add an || unset clifilename here?
-(( verbose )) && read -rp "[verbose] \$clifilename: ${clifilename:-null}"
+  local clifilepath clifilename clifiledir clipath mvoutput mvec  ## not sure what to do here.  need to see the scope of these variables.
+  if [[ ! "$1" ]]; then
+    allfiles=(*mp3)
+   (( "${#allfiles[@]}" != 1 )) && { printf '${#allfiles[@]} != 1\n'; exit 1; }
+   set -- "$allfiles"
+  fi 
+
+  [[ -e "$1" ]] && clifilepath="$(realpath "$1")"  #if a filename is passed via the cli.  this doesn't work anymore now with -t??
+read -rp "\$clifilepath is $clifilepath"
+
+
+(( verbose )) && read -rp "[verbose] \$clifilepath: ${clifilepath:-null}"
+  [[ -d "$clifilepath" ]] && clipath="${clifilepath%/}" && cd "$clipath" && unset clifilepath
+  [[ -f "$clifilepath" ]] && clipath="${clifilepath%/*}" && cd "$clipath" && clifilepath="${clifilepath##*/}" ## add an || unset clifilepath here?
+(( verbose )) && read -rp "[verbose] \$clifilepath: ${clifilepath:-null}"
 (( verbose )) && read -rp "[verbose] \$clipath: ${clipath:-null}"
 
 #  if [[ "$clipath" ]]; then
@@ -47,8 +56,7 @@ filecheck(){
       eza -glaa .
       if ! sudo -n chown -R "$USER":"${group:-$USER}" .; then
         (( verbose )) && printf '[WARN] The `sudo -n chown -R "%s":"%s" .` command failed!\n' "$USER" "${group:-$USER}"
-        (( discord )) && discorddm "m4b2opus: Attention required! confirm \`sudo chown \"$USER\" .\`"
-#       apprise "$apprisediscord" -t "Attention required m4b2opus!" -b "confirm \`sudo chown \"$USER\" .\`"
+        (( discord )) && discorddm "mp32opus: Attention required! confirm \`sudo chown \"$USER\" .\`"
         sudo chown -R "$USER":"${group:-$USER}" . || { printf '[ERROR] Cannot take ownership of %s. Investigate. (exit 1)\n' "$clipath"; exit 1; }
       fi
     fi
@@ -107,11 +115,124 @@ filecheck(){
 #      exit 1
 #    fi
 
-(( verbose )) && { printf '[verbose] Leaving filecheck():\n'; pause "          \$m4bin: $m4bin"; }
+(( verbose )) && { printf '[verbose] Leaving filecheck():\n'; [[ "$clipath" || "$clifilepath" ]] && pause "          \$clipath/\$clifilepath: $clipath/$clifilepath"; }
 #  fi
 return 0
 }
 ##--> filecheck() <--#################################################################################
+
+
+
+filecheck(){
+(( verbose )) && printf '[verbose] Entering filecheck().\n'
+  local clifilepath clifile  clidir clipath mvoutput mvec  ## not sure what to do here.  need to see the scope of these variables.
+  if [[ ! "$1" ]]; then
+    allfiles=(*.@(mp3|m4@(a|b)))
+    (( "${#allfiles[@]}" != 1 )) && { printf '${#allfiles[@]} != 1\n'; exit 1; }
+    set -- "$allfiles"
+  fi
+
+  [[ -e "$1" ]] && clifilepath="$(realpath "$1")"  #if a filename is passed via the cli.  this doesn't work anymore now with -t??
+read -rp "\$clifilepath is $clifilepath"
+
+
+(( verbose )) && read -rp "[verbose] \$clifilepath: ${clifilepath:-null}"
+  [[ -d "$clifilepath" ]] && clidir="$clifilepath" && cd "$clidir" && unset clifilepath
+  [[ -f "$clifilepath" ]] && { clifile="$(basename "$clifilepath")"; clidir="$(dirname "$clifilepath")"; cd "$clidir" || exit 1; } ## add an || unset clifilepath here?
+(( verbose )) && read -rp "[verbose] \$clifilepath: ${clifilepath:-null}"
+(( verbose )) && read -rp "[verbose] \$clipath: ${clipath:-null}"
+(( verbose )) && read -rp "[verbose] \$clidir: ${clidir:-null}"
+(( verbose )) && read -rp "[verbose] \$clifile: ${clifile:-null}"
+
+#  if [[ "$clipath" ]]; then
+#    [[ -d "$clipath" && ! -w "$clipath" ]] && { own "$clipath" || { printf 'Cannot take ownership of %s. Investigate. (exit 1)' "$clipath"; exit 1; }; }
+
+  if ! [[ -w . ]]; then
+    printf '\n[WARN] The pwd\n(%s)\n is not writable; attempting to take ownership.\n\n' "$(pwd)"
+
+    (( verbose )) && pause "[verbose] $(type own) $(which own)"
+
+    (( rmmatch )) && { own --force .; :; } || own .
+
+    if ! [[ -w . ]]; then
+      (( verbose )) && printf '\n[WARN] The `own .` command failed\n\nTrying `sudo chown $USER .`\n\n' &&
+      eza -glaa .
+      if ! sudo -n chown -R "$USER":"${group:-$USER}" .; then
+        (( verbose )) && printf '[WARN] The `sudo -n chown -R "%s":"%s" .` command failed!\n' "$USER" "${group:-$USER}"
+        (( discord )) && discorddm "mp32opus: Attention required! confirm \`sudo chown \"$USER\" .\`"
+        sudo chown -R "$USER":"${group:-$USER}" . || { printf '[ERROR] Cannot take ownership of %s. Investigate. (exit 1)\n' "$clipath"; exit 1; }
+      fi
+    fi
+    ! [[ -w . ]] && { printf '[ERROR] Cannot take ownership of %s. Investigate. (exit 1)\n' "$clipath"; exit 1; } || printf '\nOwnership of pwd granted to %s.\n' "$USER"
+  fi
+
+
+  [[ ! -w "$clifile" ]] && (( discord )) && {
+    discorddm "mp32opus notification: ${clifile:-${allfiles[0]:-title unavailable}} not writeable.";
+    printf 'mp32opus notification: %s not writeable.\n' "${clifile:-${allfiles[0]:-title unavailable}}"; }
+    read -rp "Need to implement an own step here; continue..."
+
+
+
+##  [[ "$clifilename" = *\ --\ Audiobook.m4b ]] && [[ -f "$1" ]] && m4bin="$1" && return 0
+#  [[ "$clifilename" = *\ --\ Audiobook.m4b ]] && [[ -f "$clifilename" ]] && { m4bin="$clifilename"; return 0; }
+#
+### at this point the pwd should either be the swd or it should be the local "$clipath" from the cd "$clipath" above.
+#(( verbose )) && read -rp "[verbose] \$(pwd): $(pwd)"
+#
+#  [[ "$clifilename" ]] && files=("$clifilename") || files=(*.m4[ba])
+#
+#(( verbose )) && read -rp "[verbose] \${files[@]}: $(printf %s\\n "${files[@]}")"
+#
+#    if (( "${#files[@]}" == 1 )); then
+#
+#      # to handle the case where there's an unindexed m4a or a misnamed m4b,
+#      # for simplicity sake, just rename to m4b
+#      # probably want to change it back at the end, but it is going to get deleted anyway
+#      if [[ "${files[0]}" = *.m4a ]]; then
+#        startm4a="${files[0]}"
+#        startfile="$startm4a"
+#        files[0]="${files[0]%.m4a}.m4b"
+#        mv "$startm4a" "${files[0]}"
+#        (( "$?" )) && { printf 'The starting file was an m4a which could not be renamed to m4b:\n mv %s %s\nInvestigate. (return 1)' "${startm4a@Q}" "${files[0]@Q}"; return 1; }
+#      fi
+#
+#      if [[ "${files[0]}" = *\ --\ Audiobook.m4b ]]; then
+#        m4bin="${files[0]}"
+#      elif [[ "${files[0]}" = *.m4b ]]; then
+#        m4bin="${files[0]}"
+###        startfile="${files[0]}"
+###   is there any reason I need to do this?
+###   could I make this conditional on ! (( save ))?
+###        m4bin="${files[0]/.m4b/ -- Audiobook.m4b}"
+###        mvoutput="$(mv "${files[0]}" "$m4bin" 2>&1)"
+#        mvec="$?"
+#        if (( mvec > 0 )); then
+#          if [[ "$mvoutput" = "mv: cannot move "*": Permission denied" ]]; then
+#            own && mv "${files[0]}" "$m4bin" || { printf 'Unable to gain write permission for %s. exit 1\n\n' "${files[@]}"; exit 1; }
+#          else
+#            printf 'Unknown error renaming %s. exit 1\n\n' "${files[@]}"
+#            exit 1
+#          fi
+#        fi
+#      else
+#        printf 'The file passed to the script was not an *m4[a|b]:\n %s\n.  This cannot be allowed to stand!\n\nInvestigate. (return 1)\n' "$1"
+#        return 1
+#      fi
+#    else
+#      printf 'No single m4b/m4a input file found or specified, please check and retry...\n\n'
+#      eza -laa --no-user
+#      printf '\n(exit 1)\n\n'
+#      exit 1
+#    fi
+
+  printf 'Leaving %s()\n' "$FUNCNAME"
+(( verbose )) && { printf '[verbose] Leaving filecheck():\n'; [[ "$clidir" || "$clifile" ]] && pause "          \$clidir/\$clifile: $clidir/$clifile"; }
+#  fi
+return 0
+}
+##--> filecheck() <--#################################################################################
+
 
 extractcover(){
   local file="$1"
@@ -153,7 +274,11 @@ extractcover(){
   fi
 }
 
-##--> extractcover() <--#############################################################################
+##--> extractcover() <--##############################################################################
+
+
+## main code###### ###################################################################################
+
 
 ## flag processing ###################################################################################
 
@@ -170,19 +295,20 @@ while (( $# > 0 )); do
   [[ "$1" = @(-|--)@(ys|yes) ]] && { args+=("-y"); (( screened=rmmatch=1 )); args+=(--save); shift; continue; }
   [[ "$1" = @(-|--)@(Ys|Yes) ]] && { args+=("-Y"); (( screened=rmmatch=1 )); shift; continue; }
   [[ "$1" =  @(-v|--verbose) ]] && { args+=("$1"); verbose=1; shift; continue; }
-  [[ "$1" =  @(-D|--discord) ]] && { args+=("$1"); unset discord; . ~/.config/apprise.conf; shift; continue; }
+  [[ "$1" =  @(-D|--discord) ]] && { args+=("$1"); unset discord; . ~/.config/discord-local.conf; shift; continue; }
   [[ -d "$1" ]] && { args+=("$1"); clipath="$1"; clidir="$1"; shift; continue; }
   [[ -f "$1" ]] && { args+=("$1"); clipath="$1"; clifile="$1"; shift; continue; }
   { printf '"%s" is unrecognized.\n' "$1"; shift; confirm -y 'Proceed with script?' || exit 1; }
 done
+
 
 [[ ! "$clifile" ]] && { allm4s=(*.m4[ab])
                         printf '\n%s/*.m4[ab]: \n%s' "$(pwd)" "$red"
                         printf ' %s\n' "${allm4s[@]}"
                         printf '%s' "$white"; }
 
-filecheck "${clifile:-""}"
-(( "$?" )) && { printf 'The files failed filecheck()!\nInvestigate (exit 1)\n.'; exit 1; }  # this function returns "$m4bin"
+filecheck "${clipath:-""}"
+(( "$?" )) && { printf 'The files failed filecheck()!\nInvestigate (exit 1)\n.'; exit 1; }
 
 printline "$bold  Welcome to ${0##*\/}  $tput0"
 printf \\n
@@ -223,6 +349,8 @@ allfiles=(*.@(mp3|m4@(a|b)))
 [[ "$rmmatch" ]] && args=("-y") || unset args  #this resets args from "$@"
 
 if [[ "$clifile" ]] || (( "${#allfiles[@]}" == 1 )); then
+  [[ ! -w "$allfiles" ]] && (( discord )) && discorddm "mp32opus notification: ${title:-${allfiles[0]:-title unavailable}} not writeable."
+
   (( save )) && args+=(--save)
   (( verbose )) && args+=(-v)
   args+=(-D) ## unset the discord flag since this should be doing the notification.
@@ -241,7 +369,7 @@ else
   printf \\n
   printline "${bold}  Calling ${white}opus.book.4 ${args[@]}  ${tput0}"
   clear -x
-  readarray -t initdurations < <(mediaduration)
+  readarray -t initdurations < <(mediaduration --durations)
   printf %s\\n "${initdurations[@]}"
 
 ## this check is a false sense of security as there's no way at present to check if there's not more than
@@ -294,6 +422,7 @@ else
 ## This is yet to be implemented in opus.book.4 as above...
   cd "$swd" >/dev/null || { printf 'Failure to return to SWD after indexopus! Investigate. (exit 1)\n'; exit 1; }
 
+  (( verbose )) && printf 'The $(pwd) is: %s\n' "$(pwd)"
 
   printline "${bold}  ${white}Checking durations  ${tput0}"
   printf \\n
@@ -315,8 +444,13 @@ else
   fi
 
   sourceext="${durations[0]% files*}"; sourceext="${sourceext#*of }"
-  sourcedur="${durations[0]#*: }"
-  opusdur="${durations[${opuskey:--1}]#*: }"
+#  sourcedur="${durations[0]#*: }"
+  sourcedur="${durations[0]##* }"
+#  opusdur="${durations[${opuskey:--1}]#*: }"
+  opusdur="${durations[${opuskey:--1}]##* }"
+
+  (( verbose )) && pause "$(printf '[verbose] $sourcedur="%s"\n[verbose] $opusdur="%s"\n' "$sourcedur" "$opusdur")"
+
 
   opusdursec="$(sex2sec "$opusdur")"
   sourcedursec="$(sex2sec "$sourcedur")"
